#!/bin/bash
# Trivial script to dump some information it's hard to get in within
# Travis

echo "In $0: ruby --version =" `ruby --version`

echo "In $0: SHELL = $SHELL"

echo "In $0: 'make' version is:"
make --version

echo "In $0: trying to execute 'make apisrc'"
make apisrc
