#!/bin/bash
# Trivial script to dump some information it's hard to get in within
# Travis

echo ; echo "In $0: SHELL = $SHELL"

echo ; echo "In $0: 'make' version is:"
make --version

echo ; echo "In $0: trying to execute 'make -f mf.test'"
make -f mf.test

#echo "In $0: ruby --version =" `ruby --version`

#echo ; echo "In $0: /bin/pwd = `/bin/pwd`"
#echo ; echo 'In $0: Trying to determine dependencies of OpenCL_API.txt using exactly the same commands as the Makefile $(shell) invocation:'
#GENERATED=gen
#APISPEC=OpenCL_API
#grep '^include::' $APISPEC.txt | sed -e 's/^include:://' -e 's/\[\]/ /' -e "s#{generated}#$GENERATED#" | xargs echo
