#!/bin/bash
#
# Copyright 2013-2024 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# This is a temporary method of marshalling names of all extensions
# incorporated in the spec to date (e.g. those with extension appendices),
# and will be replaced by scanning cl.xml
EXTENSIONS=`cd api && echo cl_*.asciidoc | sed -e 's/\.asciidoc//g'`

echo EXTENSIONS="$EXTENSIONS"

make EXTENSIONS="$EXTENSIONS" $*
