// Copyright 2017-2026 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[appendix]
[[changes_to_opencl]]
= Changes to OpenCL

Changes to the OpenCL C specifications between successive versions are
summarized below.

== Summary of Changes to OpenCL 3.0

The first non-experimental version of the OpenCL 3.0 specifications was *v3.0.5*.

Changes from *v3.0.5*:

  * Clarified that `memory_scope_all_devices` is supported only for OpenCL C 3.0 or newer.
  * Defined ULP overflow leniency.
  * Removed a confusing phrase about kernel argument pointer types.
  * Clarified usage of feature test macros pre-OpenCL C 3.0.
  * Clarified relationship between optional core features and extensions.
  * Deprecated the `+__OPENCL_C_VERSION__+` predefined macro and clarified possible values of the macro for different versions of OpenCL.

Changes from *v3.0.6*:

  * Clarified the argument to *vec_step* is not evaluated.
  * Improved description for pipe specifier.
  * Fixed parameter name in *work_group_broadcast* description.
  * Clarified that the size of a pipe is implementation-defined.
  * Moved descriptions of the identify value for exclusive scans.
  * Fixed several bugs and formatting in the fast math ULP tables.
  * Clarified the behavior of *work_group_broadcast*.
  * Clarified the minimum OpenCL C version for the `opencl_unroll_hint` attribute.

Changes from *v3.0.7*:

  * Clarified optionality support for double-precision literals.

Changes from *v3.0.14*:

  * Improved capitalization and hyphenation consistency throughout the specs, see {khronos-opencl-pr}/902[#902].
  * Clarified that the *nextafter* built-in function works with all floating-point types, see {khronos-opencl-pr}/953[#953].
  * Clarified that the async copy and wait group events built-in functions must be called within converged control flow, see {khronos-opencl-pr}/1015[#1015].
  * Removed unnecessary rounding mode text from the descriptions of the geometric and common functions, see {khronos-opencl-pr}/1027[#1027].

Changes from *v3.0.15*:

  * Moved all KHR extension text out of the OpenCL Extension specification and into the main specifications.
    The OpenCL Extension specification will be removed in a subsequent revision.
  * Fixed the derived formula for `atanh`, see {khronos-opencl-pr}/1048[#1048].
  * Removed an incorrect statement about geometric functions operating component-wise, see {khronos-opencl-pr}/1137[#1137].
  * Added new extension:
      ** {cl_khr_kernel_clock_EXT} (experimental)

Changes from *v3.0.16*:

  * Documented the error bounds for a non-derived `atan2` implementation with unsafe math optimizations, see {khronos-opencl-pr}/1073[#1073].
  * Fixed a typo affecting `EPSILON` macros, see {khronos-opencl-pr}/1225[#1225].

Changes from *v3.0.17*:

  * Fixed formatting issues in the builtins table for `ldexp` and `mix`, see {khronos-opencl-pr}/1290[#1290].
  * Updated the ULP requirements for the half-precision divide and reciprocal, see {khronos-opencl-pr}/1293[#1293].
  * Fixed a typo in the address space conversion example, see {khronos-opencl-pr}/1322[#1322].
  * Clarified the unsafe math accuracy requirements for the embedded profile, see {khronos-opencl-pr}/1318[#1318].
  * Clarified the data types that are supported for explicit conversions, see {khronos-opencl-pr}/1340[#1340].
  * Clarified image conversion rules for signed and unsigned image channel data types, see {khronos-opencl-pr}/1348[#1348].

Changes from *v3.0.18*:

  * Fixed an incorrect argument type for the *fast_distance* function, see {khronos-opencl-pr}/1374[#1374].
  * Updated the ULP requirements for the half-precision square root, see {khronos-opencl-pr}/1386[#1386].
  * Updated the ULP requirements for the half-precision tangent, see {khronos-opencl-pr}/1387[#1387].

== Summary of Changes from OpenCL 3.0 to OpenCL 3.1

OpenCL 3.1 adds the OpenCL 3.1 C kernel language.

Other changes in OpenCL 3.1:

  * Added support for the *z* and *t* `printf` length specifiers, see {khronos-opencl-issue}/654[#654].
  * Removed a few references to SPIR-V that do not belong in OpenCL C spec, see {khronos-opencl-pr}/1517[#1517].
  * Fixed a typo for `fmin` for the `half` type, see {khronos-opencl-pr}/1519[#1519].
  * Removed the Extending Attribute Qualifiers section, see {khronos-opencl-pr}/1532[#1532].
  * Moved the documentation of cluster size restrictions to improve readability, see {khronos-opencl-pr}/1535[#1535].
  * Clarified behavior for NaN to integer saturated conversions, see {khronos-opencl-pr}/1546[#1546].
  * Promoted the following extensions to the core API:
      ** {cl_khr_extended_bit_ops_EXT}
      ** {cl_khr_integer_dot_product_EXT}
      ** {cl_khr_subgroup_extended_types_EXT}
      ** {cl_khr_subgroup_rotate_EXT}
      ** {cl_khr_subgroup_shuffle_EXT}
      ** {cl_khr_subgroup_shuffle_relative_EXT}
