// Copyright 2017-2023 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[appendix]
[[changes_to_opencl]]
= Changes to OpenCL

Changes to the OpenCL C specifications between successive versions are
summarized below.

== Summary of changes from OpenCL 3.0

The first non-provisional version of the OpenCL 3.0 specifications was *v3.0.5*.

Changes from *v3.0.5*:

  * Clarified that `memory_scope_all_devices` is supported only for OpenCL C 3.0 or newer.
  * Defined ULP overflow leniency.
  * Removed a confusing phrase about kernel argument pointer types.
  * Clarified usage of feature test macros pre-OpenCL C 3.0.
  * Clarified relationship between optional core features and extensions.
  * Deprecated the `+__OPENCL_C_VERSION__+` predefined macro and clarified possible values of the macro for different versions of OpenCL.

Changes from *v3.0.6*:

  * Clarified the argument to *vec_step* is not evaluated.
  * Improved description for pipe specifier.
  * Fixed parameter name in *work_group_broadcast* description.
  * Clarified that the size of a pipe is implementation-defined.
  * Moved descriptions of the identify value for exclusive scans.
  * Fixed several bugs and formatting in the fast math ULP tables.
  * Clarified the behavior of *work_group_broadcast*.
  * Clarified the minimum OpenCL C version for the `opencl_unroll_hint` attribute.

Changes from *v3.0.7*:

  * Clarified optionality support for double-precision literals.

Changes from *v3.0.14*:

  * Improved capitalization and hyphenation consistency throughout the specs, see {khronos-opencl-pr}/902[#902].
  * Clarified that the *nextafter* built-in function works with all floating-point types, see {khronos-opencl-pr}/953[#953].
  * Clarified that the async copy and wait group events built-in functions must be called within converged control flow, see {khronos-opencl-pr}/1015[#1015].
  * Removed unnecessary rounding mode text from the descriptions of the geometric and common functions, see {khronos-opencl-pr}/1027[#1027].
