:data-uri:
:icons: font
include::../config/attribs.txt[]
:source-highlighter: coderay

= cl_arm_protected_memory_allocation

== Name Strings

`cl_arm_protected_memory_allocation`

== Contact

Kevin Petit (kevin.petit 'at' arm.com)

== Contributors

Kevin Petit, Arm Ltd. +

== Notice

Copyright (c) 2021-2024 Arm Ltd.

== Status

Shipping

== Version

Built On: {docdate} +
Version: 1.0.0

== Dependencies

This extension is written against the OpenCL Specification version 3.0.6.

This extension requires OpenCL 1.2.

== Overview

This extensions enables the creation of buffers and images backed by protected
memory, i.e. memory protected using TrustZone Media Protection.

== New API Enums

New flag added to `cl_mem_flags`:

[source,c]
----
CL_MEM_PROTECTED_ALLOC_ARM       (1 << 36)
----

== Modifications to the OpenCL API Specification

(Modify Section 5.2.1, *Creating Buffer Objects*) ::
+
--

(Add the following to Table 12, _List of supported memory flag values_) ::
+
--

[cols="1,1",options="header"]
|====
| Memory flags
| Description

| `CL_MEM_PROTECTED_ALLOC_ARM`
| Specifies that the memory object being created will be backed by protected
  memory. When this flag is present, the only host flag allowed is
  `CL_MEM_HOST_NO_ACCESS`. If host flags are omitted, `CL_MEM_HOST_NO_ACCESS`
  is assumed.

|====

--
--

== Interactions with Other Extensions

None.

== Conformance tests

None.

== Issues

None.

== Version History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|====
| Version | Date       | Author       | Changes
| 1.0.0   | 2021-07-09 | Kevin Petit  | *Initial revision*
|====

