// Copyright 2018-2024 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

:data-uri:
:icons: font
include::../config/attribs.txt[]
:source-highlighter: coderay

= cl_ext_cxx_for_opencl
:R: pass:q,r[^(R)^]
Khronos{R} OpenCL Working Group

== Name Strings

`cl_ext_cxx_for_opencl`

== Contact

Please see the *Issues* list in the Khronos *OpenCL-Docs* repository: +
https://github.com/KhronosGroup/OpenCL-Docs

== Contributors

Kevin Petit, Arm Ltd. +
Sven Van Haastregt, Arm Ltd. +
Anastasia Stulova, Arm Ltd. +
Marco Antognini, Arm Ltd. +
Neil Hickey, Arm Ltd. +
Alastair Murray, Codeplay +

== Notice

include::../copyrights.txt[]

== Version

Built On: {docdate} +
Version: 1.0.0

== Dependencies

This extension is written against the OpenCL Specification
Version 3.0.3.

This extension requires OpenCL 3.0 with OpenCL C 2.0 support or OpenCL 2.x and
`cl_khr_extended_versioning`.

== Overview

This extension adds support for building programs written using the C++ for
OpenCL kernel language documented in the *OpenCL-Docs* repository
(https://github.com/KhronosGroup/OpenCL-Docs)
with stable versions published in releases of the repository.

This extension also enables applications to query the version of the language
supported by the device compiler.

== New build option

This extension adds support for a new `CLC++` value to be passed to the
`-cl-std` build option accepted by *clBuildProgram* and *clCompileProgram*.

== New API Enums

Accepted value for the _param_name_ parameter to *clGetDeviceInfo*:

[source,c]
----
CL_DEVICE_CXX_FOR_OPENCL_NUMERIC_VERSION_EXT       0x4230
----

== Preprocessor Macros

This extension defines a new language, instead of extending an existing
language. As such, there will be no preprocessor `#define` matching the
extension name string. Instead, dedicated preprocessor macros conveying
language version information are available as described in the C++ for
OpenCL Programming Language Documentation, section 2.2.2.2 "Predefined
macros".


== Modifications to the OpenCL API Specification

(Modify Section 4.2, *Querying Devices*) ::
+
--

(Add the following to Table 4.3, _Device Queries_) ::
+
--

[cols="1,1,4",options="header"]
|====
| cl_device_info
| Return Type
| Description

| `CL_DEVICE_CXX_FOR_OPENCL_NUMERIC_VERSION_EXT`
| `cl_version`
| Returns the version of the C++ for OpenCL language supported by the
  device compiler.

|====

--
--

(Modify Section 5.8.1, *Creating Program Objects*) ::
+
--
Add the following text to the description for *clCreateProgramWithSource*:

The source code specified by _strings_ may also be a C++ for OpenCL program source
or header.
--

(Modify section to 5.8.6, *Compiler Options*) ::
+
--

(Add subsection, *C++ for OpenCL*) ::
+
--
Applications may pass `-cl-std=CLC\++` to *clCompileProgram* and *clBuildProgram*
for programs created using *clCreateProgramFromSource* to request the program
be built as C++ for OpenCL.
--

--

== Conformance tests

. Test that a program can successfully be compiled with `-cl-std=CLC++`.
. Test with a program compiled with `-cl-std=CLC++` that the value of the
  +__OPENCL_CPP_VERSION__+ macro agrees with the version returned by
  `CL_DEVICE_CXX_FOR_OPENCL_NUMERIC_VERSION_EXT`.

== Issues

None.

== Version History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|====
| Version | Date       | Author       | Changes
| 1.0.0   | 2020-08-25 | Kevin Petit  | *Initial revision*
|====

