= cl_intel_spirv_device_side_avc_motion_estimation

// This section needs to be after the document title.
:doctype: book
:toc2:
:toc: left
:encoding: utf-8
:lang: en

:blank: pass:[ +]

// Set the default source code type in this document to C++,
// for syntax highlighting purposes.  This is needed because
// docbook uses c++ and html5 uses cpp.
:language: {basebackend@docbook:c++:cpp}

== Name Strings

`cl_intel_spirv_device_side_avc_motion_estimation`

== Contact

Ben Ashbaugh, Intel (ben 'dot' ashbaugh 'at' intel 'dot' com)

== Contributors

Ben Ashbaugh, Intel +
Biju George, Intel

== Notice

Copyright (c) 2018-2024 Intel Corporation.  All rights reserved.

== Status

Final Draft

== Version

Built On: {docdate} +
Revision: 2

== Dependencies

This extension is written against the OpenCL SPIR-V Environment Specification Version 2.2, Revision v2.2-3.

This extension requires OpenCL support for SPIR-V, either via OpenCL 2.1 or via the `cl_khr_il_program` extension, and support for the `cl_intel_device_side_avc_motion_estimation` extension.

== Overview

This extension defines how modules using the SPIR-V extension `SPV_INTEL_device_side_avc_motion_estimation` may behave in an OpenCL environment.

This extension is a companion to the `cl_intel_device_side_avc_motion_estimation` OpenCL extension, and the functionality described in this extension and `SPV_INTEL_device_side_avc_motion_estimation` is sufficient to implement the built-in functions defined in the `cl_intel_device_side_avc_motion_estimation` extension.

== New API Functions

None.

== New API Enums

None.

== Modifications to the OpenCL SPIR-V Environment Specification

=== Add a new Section 7.1.X - `cl_intel_spirv_device_side_avc_motion_estimation`

If the OpenCL environment supports the extension `cl_intel_spirv_device_side_avc_motion_estimation`, then the environment must accept SPIR-V modules that declare use of the `SPV_INTEL_device_side_avc_motion_estimation` extension via *OpExtension*.

If the OpenCL environment supports the extension `cl_intel_spirv_device_side_avc_motion_estimation` and use of the `SPV_INTEL_device_side_avc_motion_estimation` extension is declared in the module via *OpExtension*, then the environment must accept modules that declare the following SPIR-V capabilities:

* *SubgroupAvcMotionEstimationINTEL*
* *SubgroupAvcMotionEstimationIntraINTEL*
* *SubgroupAvcMotionEstimationChromaINTEL*

== Issues

None.

//. Title
//+
//--
//*RESOLUTION*: Description
//--

== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2018-10-29|Ben Ashbaugh|*Initial revision*
|2|2019-09-17|Ben Ashbaugh|Minor formatting fixes for asciidoctor.
|========================================

//************************************************************************
//Other formatting suggestions:
//
//* Use *bold* text for host APIs, or [source] syntax highlighting.
//* Use `mono` text for device APIs, or [source] syntax highlighting.
//* Use `mono` text for extension names, types, or enum values.
//* Use _italics_ for parameters.
//************************************************************************
