cl_intel_mem_channel_property
=============================

// This section needs to be after the document title.
:doctype: book
:toc2:
:toc: left
:encoding: utf-8
:lang: en

:blank: pass:[ +]

// Set the default source code type in this document to C++,
// for syntax highlighting purposes.  This is needed because
// docbook uses c++ and html5 uses cpp.
:language: {basebackend@docbook:c++:cpp}

Name Strings
------------

+cl_intel_mem_channel_property+

Contact
-------

Kris Kang, Intel (kris 'dot' kang 'at' intel 'dot' com)

Contributors
------------

* David Cashman, Intel
* Michael Kinsner, Intel
* Peter Yiannacouras, Intel
* Ben Ashbaugh, Intel
* Kris Kang, Intel

Notice
------

Copyright (c) 2020-2025 Intel Corporation. All rights reserved.

Status
------

Final Draft

Version
-------

[width="40%",cols="25,25"]
|========================================
| Last Modified | 2020-05-29
| Revision      | 1
|========================================

Dependencies
------------

This extension is written against the OpenCL Specification Version 1.0, Revision 48.

This extension requires OpenCL 1.0 or later and the cl_intel_create_buffer_with_properties extension.

Overview
--------

On some accelerators, manual partitioning of buffers across different regions
of memory may result in higher performance by spreading high-demand 
memory across different interfaces or ports of a memory.

This extension allows programmers to request that
a buffer allocation be implemented in a particular region of memory.

New API Functions
-----------------

None.

New API Enums
-------------

Accepted property for the _properties_ parameter to *clCreateBufferWithPropertiesINTEL* to specify the requested channel for the buffer:

[source,c]
----
#define CL_MEM_CHANNEL_INTEL        0x4213
----

Modifications to the OpenCL API Specification
---------------------------------------------

(Add Table 5.X: *List of supported properties by clCreateBufferWithPropertiesINTEL* to the cl_intel_create_buffer_with_properties extension) ::
+

[cols="1,1,4",options="header",width = "90%"]
|====
| cl_mem_properties_intel enum
| Property value
| Description

| +CL_MEM_CHANNEL_INTEL+
| +cl_uint+
| Identifies the channel/region to which the buffer should be mapped.  The range of legal values is implementation-defined.  This parameter acts as a hint: if the value is not valid, or the implementation is unable to allocate memory in the requested region, it may be ignored without emission of any warning or error.
|====


Issues
------

None.

Revision History
----------------

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2020-05-29|Kris Kang|*Initial public release*
|========================================

