// Copyright 2017-2024 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[[cl_khr_priority_hints]]
== Priority Hints

This section describes the *cl_khr_priority_hints* extension.
This extension adds priority hints for OpenCL, but does not specify the
scheduling behavior or minimum guarantees.
It is expected that the the user guides associated with each implementation
which supports this extension will describe the scheduling behavior
guarantees.

=== General Information

==== Version History

[cols="1,1,3",options="header",]
|====
| *Date*     | *Version* | *Description*
| 2020-04-21 | 1.0.0     | First assigned version.
|====

[[cl_khr_priority_hints-host-side-api-modifications]]
=== Host-side API modifications

The function {clCreateCommandQueueWithProperties} (Section 5.1) is
extended to support a priority value as part of the _properties_ argument.

The priority property applies to OpenCL command-queues that belong to the
same OpenCL context.

The properties field accepts the {CL_QUEUE_PRIORITY_KHR} property, with a
value of type {cl_queue_priority_khr_TYPE}, which can be one of:

  * {CL_QUEUE_PRIORITY_HIGH_KHR}
  * {CL_QUEUE_PRIORITY_MED_KHR}
  * {CL_QUEUE_PRIORITY_LOW_KHR}

If {CL_QUEUE_PRIORITY_KHR} is not specified then the default priority is
{CL_QUEUE_PRIORITY_MED_KHR}.

To the error section for {clCreateCommandQueueWithProperties}, the
following is added:

  * {CL_INVALID_QUEUE_PROPERTIES} if the {CL_QUEUE_PRIORITY_KHR} property is
    specified and the queue is a {CL_QUEUE_ON_DEVICE}.
