// Copyright 2017-2024 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[[cl_khr_throttle_hints]]
== Throttle Hints

This section describes the *cl_khr_throttle_hints* extension.
This extension adds throttle hints for OpenCL, but does not specify the
throttling behavior or minimum guarantees.
It is expected that the user guide associated with each implementation which
supports this extension will describe the throttling behavior guarantees.

Note that the throttle hint is orthogonal to functionality defined in
*cl_khr_priority_hints* extension.
For example, a task may have high priority ({CL_QUEUE_PRIORITY_HIGH_KHR})
but should at the same time be executed at an optimized throttle setting
({CL_QUEUE_THROTTLE_LOW_KHR}).

=== General Information

==== Version History

[cols="1,1,3",options="header",]
|====
| *Date*     | *Version* | *Description*
| 2020-04-21 | 1.0.0     | First assigned version.
|====

[[cl_khr_throttle_hints-host-side-api-modifications]]
=== Host-side API modifications

The function {clCreateCommandQueueWithProperties} (Section 5.1) is
extended to support a new {CL_QUEUE_THROTTLE_KHR} value as part of the
_properties_ argument.

The properties field accepts the following values:

  * {CL_QUEUE_THROTTLE_HIGH_KHR} (full throttle, i.e., OK to consume more
    energy)
  * {CL_QUEUE_THROTTLE_MED_KHR} (normal throttle)
  * {CL_QUEUE_THROTTLE_LOW_KHR} (optimized/lowest energy consumption)

If {CL_QUEUE_THROTTLE_KHR} is not specified then the default priority is
{CL_QUEUE_THROTTLE_MED_KHR}.

To the error section for {clCreateCommandQueueWithProperties}, the
following is added:

  * {CL_INVALID_QUEUE_PROPERTIES} if the {CL_QUEUE_THROTTLE_KHR} property is
    specified and the queue is a {CL_QUEUE_ON_DEVICE}.
