// Copyright 2017-2024 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[[cl_khr_int32_atomics]]
== 32-bit Atomics

This section describes the extensions *cl_khr_global_int32_base_atomics*, *cl_khr_global_int32_extended_atomics*, *cl_khr_local_int32_base_atomics*, and *cl_khr_local_int32_extended_atomics*.
These extensions allow atomic operations to be performed on 32-bit signed and unsigned integers in global and local memory.

These extensions became core features in OpenCL 1.1, except the built-in atomic function names are changed to use the **atomic_** prefix instead of **atom_** and the volatile qualifier was added to the pointer parameter _p_.

=== General Information

==== Version History

[cols="1,1,3",options="header",]
|====
| *Date*     | *Version* | *Description*
| 2020-04-21 | 1.0.0     | First assigned version.
|====

=== Global Atomics for 32-bit Integers

==== Base Atomics

._Built-in Atomic Functions for_ *cl_khr_global_int32_base_atomics*
[cols="9,5",options="header",]
|=======================================================================
|*Function* |*Description*

|
int **atom_add** (volatile {global} int *_p_, int _val_) +
uint **atom_add** (volatile {global} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ + _val_) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_sub** (volatile {global} int *_p_, int _val_) +
uint **atom_sub** (volatile {global} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ - _val_) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_xchg** (volatile {global} int *_p_, int _val_) +
uint **atom_xchg** (volatile {global} uint *_p_, uint _val_)

|Swaps the _old_ value stored at location _p_ with new value given by
_val_. Returns _old_ value.

|
int **atom_inc** (volatile {global} int *_p_) +
uint **atom_inc** (volatile {global} uint *_p_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ + _1_) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_dec** (volatile {global} int *_p_) +
uint **atom_dec** (volatile {global} uint *_p_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ - _1_) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_cmpxchg** (volatile {global} int *_p_, int _cmp_, int _val_) +
uint **atom_cmpxchg** (volatile {global} uint *_p_, uint _cmp_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ == _cmp_) ? _val_ : _old_ and store
result at location pointed by _p_. The function returns _old_.

|=======================================================================

==== Extended Atomics

._Built-in Atomic Functions for_ *cl_khr_global_int32_extended_atomics*
[cols="9,5",options="header",]
|=======================================================================
|*Function* |*Description*

|
int **atom_min** (volatile {global} int *_p_, int _val_) +
uint **atom_min** (volatile {global} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute *min*(_old_, _val_) and store minimum value at
location pointed by _p_. The function returns _old_.

|
int **atom_max** (volatile {global} int *_p_, int _val_) +
uint **atom_max** (volatile {global} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute *max*(_old_, _val_) and store maximum value at
location pointed by _p_. The function returns _old_.

|
int **atom_and** (volatile {global} int *_p_, int _val_) +
uint **atom_and** (volatile {global} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ & val) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_or** (volatile {global} int *_p_, int _val_) +
uint **atom_or** (volatile {global} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ \| val) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_xor** (volatile {global} int *_p_, int _val_) +
uint **atom_xor** (volatile {global} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ ^ val) and store result at location
pointed by _p_. The function returns _old_.

|=======================================================================

=== Local Atomics for 32-bit Integers

==== Base Atomics

._Built-in Atomic Functions for_ *cl_khr_local_int32_base_atomics*
[cols="9,5",options="header",]
|=======================================================================
|*Function* |*Description*

|
int **atom_add** (volatile {local} int *_p_, int _val_) +
uint **atom_add** (volatile {local} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ + _val_) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_sub** (volatile {local} int *_p_, int _val_) +
uint **atom_sub** (volatile {local} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ - _val_) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_xchg** (volatile {local} int *_p_, int _val_) +
uint **atom_xchg** (volatile {local} uint *_p_, uint _val_)

|Swaps the _old_ value stored at location _p_ with new value given by
_val_. Returns _old_ value.

|
int **atom_inc** (volatile {local} int *_p_) +
uint **atom_inc** (volatile {local} uint *_p_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ + _1_) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_dec** (volatile {local} int *_p_) +
uint **atom_dec** (volatile {local} uint *_p_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ - _1_) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_cmpxchg** (volatile {local} int *_p_, int _cmp_, int _val_) +
uint **atom_cmpxchg** (volatile {local} uint *_p_, uint _cmp_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ == _cmp_) ? _val_ : _old_ and store
result at location pointed by _p_. The function returns _old_.

|=======================================================================

==== Extended Atomics

._Built-in Atomic Functions for_ *cl_khr_local_int32_extended_atomics*
[cols="9,5",options="header",]
|=======================================================================
|*Function* |*Description*

|
int **atom_min** (volatile {local} int *_p_, int _val_) +
uint **atom_min** (volatile {local} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute *min*(_old_, _val_) and store minimum value at
location pointed by _p_. The function returns _old_.

|
int **atom_max** (volatile {local} int *_p_, int _val_) +
uint **atom_max** (volatile {local} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute *max*(_old_, _val_) and store maximum value at
location pointed by _p_. The function returns _old_.

|
int **atom_and** (volatile {local} int *_p_, int _val_) +
uint **atom_and** (volatile {local} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ & val) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_or** (volatile {local} int *_p_, int _val_) +
uint **atom_or** (volatile {local} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ \| val) and store result at location
pointed by _p_. The function returns _old_.

|
int **atom_xor** (volatile {local} int *_p_, int _val_) +
uint **atom_xor** (volatile {local} uint *_p_, uint _val_)

|Read the 32-bit value (referred to as _old_) stored at location
pointed by _p_. Compute (_old_ ^ val) and store result at location
pointed by _p_. The function returns _old_.

|=======================================================================

