// Copyright 2017-2024 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[appendix]
== Extensions Promoted to Core Features

=== For OpenCL 1.1:

//* The OpenCL KHR extension *cl_khr_d3d10_sharing* has been added.
//* The OpenCL KHR extension *cl_khr_gl_event* has been added.

* The functionality previously described by *cl_khr_byte_addressable_store* is now part of the core feature set.
* The functionality previously described by *cl_khr_global_int32_base_atomics*, *cl_khr_global_int32_extended_atomics*, *cl_khr_local_int32_base_atomics*, and *cl_khr_local_int32_extended_atomics* is now part of the core feature set.

=== For OpenCL 1.2:

//* The OpenCL KHR extension *cl_khr_d3d11_sharing* has been added.
//* The OpenCL KHR extension *cl_khr_depth_images* has been added.
//* The OpenCL KHR extension *cl_khr_dx9_media_sharing* has been added.
//* The OpenCL KHR extension *cl_khr_egl_event* has been added.
//* The OpenCL KHR extension *cl_khr_egl_image* has been added.
//* The OpenCL KHR extension *cl_khr_gl_depth_images* has been added.
//* The OpenCL KHR extension *cl_khr_gl_msaa_sharing* has been added.
//* The OpenCL KHR extension *cl_khr_il_program* has been added.
//* The OpenCL KHR extension *cl_khr_image2d_from_buffer* has been added.
//* The OpenCL KHR extension *cl_khr_initialize_memory* has been added.
//* The OpenCL KHR extension *cl_khr_spir* has been added.
//* The OpenCL KHR extension *cl_khr_terminate_context* has been added.

* The functionality previously described by *cl_khr_fp64* is now an optional core feature.

=== For OpenCL 2.0:

//* The OpenCL KHR extension *cl_khr_device_enqueue_local_arg_types* has been added.
//* The OpenCL KHR extensions *cl_khr_mipmap_image* and *cl_khr_mipmap_image_writes* have been added.
//* The OpenCL KHR extension *cl_khr_subgroups* has been added.

* The functionality described by *cl_khr_3d_image_writes* is part of the core feature set.
* The functionality described by *cl_khr_create_command_queue* is part of the core feature set.
* The functionality described by *cl_khr_depth_images* is now part of the core feature set.
* The functionality described by *cl_khr_image2d_from_buffer* is now part of the core feature set.

=== For OpenCL 2.1:

//* The OpenCL KHR extension *cl_khr_priority_hints* has been added.
//* The OpenCL KHR extension *cl_khr_throttle_hints* has been added.

// I recall having this discussion but I don't see this extension mentioned anywhere
// in the OpenCL 2.1 spec, and it would be a language change anyhow.
//* The functionality described in *cl_khr_device_enqueue_local_arg_types* is now part of the core feature set.

* The functionality described by *cl_khr_il_program* is now part of the core feature set.
* The API functionality described by *cl_khr_subgroups* is now part of the core API feature set, but the built-in functions described by *cl_khr_subgroups* must still be accessed as an extension to the OpenCL 2.0 C Language specification.

//=== For OpenCL 2.2:
//
//* The OpenCL KHR extension *cl_khr_subgroup_named_barrier* has been added.

=== For OpenCL 3.0:

* The API functionality described by *cl_khr_extended_versioning* is now part of the core API feature set, with minor modifications.
* The built-in functions described by *cl_khr_subgroups* are now supported in OpenCL C 3.0 when the {opencl_c_subgroups} feature is supported.