ifdef::cl_khr_icd[]
endif::cl_khr_icd[]

=== Additions to Chapter 4 of the OpenCL 2.2 Specification

In _section 4.1_, replace the description of the return values of
{clGetPlatformIDs} with:

// refError

{clGetPlatformIDs} returns {CL_SUCCESS} if the function is executed
successfully and there are a non zero number of platforms available.
Otherwise, it returns one of the following errors:

  * {CL_PLATFORM_NOT_FOUND_KHR} if zero platforms are available.
  * {CL_INVALID_VALUE} if _num_entries_ is equal to zero and _platforms_ is
    not `NULL` or if both _num_platforms_ and _platforms_ are `NULL`.

In _section 4.1_, add the following after the description of
{clGetPlatformIDs}:

[open,refpage='clIcdGetPlatformIDsKHR',desc='Query platforms accessible through the Khronos ICD Loader',type='protos']
--
To obtain the list of platforms accessible through the Khronos ICD Loader,
call the function:

include::{generated}/api/protos/clIcdGetPlatformIDsKHR.txt[]

  * _num_entries_ is the number of {cl_platform_id_TYPE} entries that can be
    added to _platforms_.
    If _platforms_ is not `NULL`, then _num_entries_ must be greater than
    zero.
  * _platforms_ returns a list of OpenCL platforms available for access
    through the Khronos ICD Loader.
    The {cl_platform_id_TYPE} values returned in _platforms_ are ICD
    compatible and can be used to identify a specific OpenCL platform.
    If the _platforms_ argument is `NULL`, then this argument is ignored.
    The number of OpenCL platforms returned is the minimum of the value
    specified by _num_entries_ or the number of OpenCL platforms available.
  * _num_platforms_ returns the number of OpenCL platforms available.
    If _num_platforms_ is `NULL`, then this argument is ignored.

// refError

{clIcdGetPlatformIDsKHR} returns {CL_SUCCESS} if the function is executed
successfully and there are a non zero number of platforms available.
Otherwise, it returns one of the following errors:

  * {CL_PLATFORM_NOT_FOUND_KHR} if zero platforms are available.
  * {CL_INVALID_VALUE} if _num_entries_ is equal to zero and _platforms_ is
    not `NULL` or if both _num_platforms_ and _platforms_ are `NULL`.
--

Add the following to _table 4.1_:

[cols="2,1,2",options="header"]
|====
| *Platform Info* | *Return Type* | *Description*
| {CL_PLATFORM_ICD_SUFFIX_KHR}
  | {char_TYPE}[]
    | The function name suffix used to identify extension functions to be
      directed to this platform by the ICD Loader.
|====
