ifdef::cl_khr_extended_versioning[]
endif::cl_khr_extended_versioning[]

=== Modifications to the OpenCL API Specification

(Modify Section 4.1, *Querying Platform Info*) ::

(Add the following to Table 3, _List of supported param_names by {clGetPlatformInfo}_) ::

[cols="3,2,3",options="header"]
|====
| *Platform Info* | *Return Type* | *Description*
| {CL_PLATFORM_NUMERIC_VERSION_KHR}
  | {cl_version_khr_TYPE}
    | Returns detailed (major, minor, patch) numeric version information.
      The major and minor version numbers returned must match those returned
      via {CL_PLATFORM_VERSION}.
| {CL_PLATFORM_EXTENSIONS_WITH_VERSION_KHR}
  | {cl_name_version_khr_TYPE}[]
    | Returns an array of description (name and version) structures.
      The same extension name must not be reported more than once.
      The list of extensions reported must match the list reported via
      {CL_PLATFORM_EXTENSIONS}.
|====

(Modify Section 4.2, *Querying Devices*) ::

(Add the following to Table 5, _List of supported param_names by {clGetDeviceInfo}_) ::

[cols="3,2,3",options="header"]
|====
| *Device Info* | *Return Type* | *Description*
| {CL_DEVICE_NUMERIC_VERSION_KHR}
  | {cl_version_khr_TYPE}
    | Returns detailed (major, minor, patch) numeric version information.
      The major and minor version numbers returned must match those returned
      via {CL_DEVICE_VERSION}.
| {CL_DEVICE_OPENCL_C_NUMERIC_VERSION_KHR}
  | {cl_version_khr_TYPE}
    | Returns detailed (major, minor, patch) numeric version information.
      The major and minor version numbers returned must match those returned
      via {CL_DEVICE_OPENCL_C_VERSION}.
| {CL_DEVICE_EXTENSIONS_WITH_VERSION_KHR}
  | {cl_name_version_khr_TYPE}[]
    | Returns an array of description (name and version) structures.
      The same extension name must not be reported more than once.
      The list of extensions reported must match the list reported via
      {CL_DEVICE_EXTENSIONS}.
| {CL_DEVICE_ILS_WITH_VERSION_KHR}
  | {cl_name_version_khr_TYPE}[]
    | Returns an array of descriptions (name and version) for all supported
      Intermediate Languages.
      Intermediate Languages with the same name may be reported more than
      once but each name and major/minor version combination may only be
      reported once.
      The list of intermediate languages reported must match the list
      reported via {CL_DEVICE_IL_VERSION}.
| {CL_DEVICE_BUILT_IN_KERNELS_WITH_VERSION_KHR}
  | {cl_name_version_khr_TYPE}[]
    | Returns an array of descriptions for the built-in kernels supported by
      the device.
      Each built-in kernel may only be reported once.
      The list of reported kernels must match the list returned via
      {CL_DEVICE_BUILT_IN_KERNELS}.
|====
