[[cl_khr_subgroup_named_barrier]]
== Named Barriers for Sub-groups

*Name String*::
`cl_khr_subgroup_named_barrier`
*Revision*::
1.0.0
*Ratification Status*::
Ratified
*Extension and Version Dependencies*::
TBD
*Contact*::
  * TBD

=== Other Extension Metadata

*Last Modified Date*::
    2020-04-21
*IP Status*::
    No known IP claims.
*Contributors*::
    TBD

=== Description

`cl_khr_subgroup_named_barrier` adds barrier operations that cover subsets
of an OpenCL work-group.
Only the OpenCL API changes are described in this section.
Please refer to the SPIR-V specification for information about using
sub-groups named barriers in the SPIR-V intermediate representation, and to
the OpenCL {cpp} specification for descriptions of the sub-group named
barrier built-in functions in the OpenCL {cpp} kernel language.

=== Version History

  * Revision 1.0.0, 2020-04-21
  ** First assigned version.

=== Changes to the OpenCL Specification

Add to _table 4.3_:

.List of supported param_names by {clGetDeviceInfo}
[cols="2,1,3",options="header",]
|====
| *Device Info* | *Return Type* | *Description*
| {CL_DEVICE_MAX_NAMED_BARRIER_COUNT_KHR}
  | {cl_uint_TYPE}
    | Maximum number of named barriers in a work-group for any given
      kernel-instance running on the device.
      The minimum value is 8.
|====

