[[cl_khr_pci_bus_info]]
== PCI Bus Information Query

*Name String*::
`cl_khr_pci_bus_info`
*Revision*::
1.0.0
*Ratification Status*::
Ratified
*Extension and Version Dependencies*::
This extension requires OpenCL 1.0.
*Contact*::
  * TBD

=== Other Extension Metadata

*Last Modified Date*::
    2021-04-19
*IP Status*::
    No known IP claims.
*Contributors*::
    TBD

=== Description

`cl_khr_pci_bus_info` adds a new query to obtain PCI bus information about
an OpenCL device.

Not all OpenCL devices have PCI bus information, either due to the device
not being connected to the system through a PCI interface or due to platform
specific restrictions and policies.
Thus this extension is only expected to be supported by OpenCL devices which
can provide the information.

As a consequence, applications should always check for the presence of the
extension string for each individual OpenCL device for which they intend to
issue the new query for and should not have any assumptions about the
availability of the extension on any given platform.

=== New Types

  * {cl_device_pci_bus_info_khr_TYPE}

=== New Enums

  * {cl_device_info_TYPE}
  ** {CL_DEVICE_PCI_BUS_INFO_KHR}

=== Version History

  * Revision 1.0.0, 2021-04-19
  ** Initial version.


=== Modifications to the OpenCL API Specification

==== Section 4.2 - Querying Devices:

Add to Table 5 - OpenCL Device Queries:

[caption="Table 5. "]
.OpenCL Device Queries
[width="100%",cols="<30%,<20%,<50%",options="header"]
|====
| *DeviceInfo* | *Return Type* | *Description*
| {CL_DEVICE_PCI_BUS_INFO_KHR}
  | {cl_device_pci_bus_info_khr_TYPE}
    | Returns PCI bus information for the device.

      The PCI bus information is returned as a single structure that
      includes the PCI bus domain, the PCI bus identifier, the PCI device
      identifier, and the PCI device function identifier.

TODO - create a 'structs' refpage block for this and describe it.

[open,refpage='cl_device_pci_bus_info_khr',desc='Structure describing PCI bus information',type='structs']
--
include::{generated}/api/structs/cl_device_pci_bus_info_khr.txt[]
--
|====
