// Copyright 2017-2023 The Khronos Group.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}cl_khr_priority_hints.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2020-04-21
*IP Status*::
    No known IP claims.
*Contributors*::
    TBD

=== Description

`cl_khr_priority_hints` adds priority hints for OpenCL, but does not specify
the scheduling behavior or minimum guarantees.
It is expected that the the user guides associated with each implementation
which supports this extension will describe the scheduling behavior
guarantees.

//@ TODO Needs API summary

=== Version History

  * Revision 1.0.0, 2020-04-21
  ** First assigned version.
//HEADER



TODO Needs rewriting as actual spec language

=== Host-Side API Modifications

The function {clCreateCommandQueueWithProperties} (Section 5.1) is extended
to support a priority value as part of the _properties_ argument.

The priority property applies to OpenCL command-queues that belong to the
same OpenCL context.

The properties field accepts the {CL_QUEUE_PRIORITY_KHR} property, with a
value of type {cl_queue_priority_khr_TYPE}, which can be one of:

  * {CL_QUEUE_PRIORITY_HIGH_KHR}
  * {CL_QUEUE_PRIORITY_MED_KHR}
  * {CL_QUEUE_PRIORITY_LOW_KHR}

If {CL_QUEUE_PRIORITY_KHR} is not specified then the default priority is
{CL_QUEUE_PRIORITY_MED_KHR}.

To the error section for {clCreateCommandQueueWithProperties}, the following
is added:

  * {CL_INVALID_QUEUE_PROPERTIES} if the {CL_QUEUE_PRIORITY_KHR} property is
    specified and the queue is a {CL_QUEUE_ON_DEVICE}.
