#!/bin/sh
# -m    No timestamp
# -x    Blindly overwrite existing files
# -F    Force 'X' prefix (not used at present)
# -T    Treat all files as text
# -D    No MD5 digest

set -x
shar -mxFTD cl*asciidoc > ext.shar
