// Copyright 2017-2025 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[appendix]
[[changes_to_opencl]]
= Changes to OpenCL

Changes to the OpenCL SPIR-V Environment specifications between successive
versions are summarized below.

== Summary of changes from OpenCL 3.0

The first non-provisional version of the OpenCL 3.0 specifications was *v3.0.5*.

Changes from *v3.0.5*:

  * Clarified sub-group barrier behavior in non-uniform control flow.
  * Added required alignment of types.
  * Added new extensions:
      ** {cl_khr_subgroup_extended_types_EXT}
      ** {cl_khr_subgroup_non_uniform_vote_EXT}
      ** {cl_khr_subgroup_ballot_EXT}
      ** {cl_khr_subgroup_non_uniform_arithmetic_EXT}
      ** {cl_khr_subgroup_shuffle_EXT}
      ** {cl_khr_subgroup_shuffle_relative_EXT}
      ** {cl_khr_subgroup_clustered_reduce_EXT}

Changes from *v3.0.6*:

  * Explicitly say that *OpTypeSampledImage* may be used in an OpenCL environment.
  * Added the required type for SPIR-V built-in variables.
  * Fixed several bugs and formatting in the fast math ULP tables.
  * Added new extensions:
      ** {cl_khr_extended_bit_ops_EXT}
      ** {cl_khr_spirv_extended_debug_info_EXT}
      ** {cl_khr_spirv_linkonce_odr_EXT}

Changes from *v3.0.8*:

  * Clarified that some OpenCL `khr` extensions also require SPIR-V extensions.

Changes from *v3.0.14*:

  * Fixed several numerical compliance bugs, see {khronos-opencl-pr}/937[#937].

Changes from *v3.0.15*:

  * Clarified that 16-bit and 64-bit floats can be passed as kernel arguments to SPIR-V kernels, see {khronos-opencl-pr}/1049[#1049].
  * Adds the numerical value of the image channel order and image channel data type to several tables, see {khronos-opencl-pr}/1050[#1050].
  * Added new extension:
      ** {cl_khr_kernel_clock_EXT} (provisional)

Changes from *v3.0.16*:

  * Documented the error bounds for a non-derived `atan2` implementation with unsafe math optimizations, see {khronos-opencl-pr}/1073[#1073].
  * Documented supported `printf` operand types, see {khronos-opencl-pr}/1236[#1236].
  * Documented valid coordinate types when reading from or writing to images, see {khronos-opencl-pr}/1242[#1242].

Changes from *v3.0.17*:

  * Updated the ULP requirements for the half-precision divide and reciprocal, see {khronos-opencl-pr}/1293[#1293].
  * Clarified the unsafe math accuracy requirements for the embedded profile, see {khronos-opencl-pr}/1318[#1318].
  * Updated the SPIR-V environment for SPIR-V 1.3, 1.4, 1.5, and 1.6, see {khronos-opencl-pr}/1331[#1331].
