// Copyright 2017-2025 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[[common-properties]]
== Common Properties

This section describes common properties of all OpenCL environments that
consume SPIR-V modules.

A SPIR-V module passed to an OpenCL environment is interpreted as a series
of 32-bit words in host endianness, with literal strings packed as described
in the SPIR-V specification.
The first few words of the SPIR-V module must be a magic number and a SPIR-V
version number, as described in the SPIR-V specification.

=== Supported SPIR-V Versions

An OpenCL environment describes the versions of SPIR-V modules that it
supports using the {CL_DEVICE_IL_VERSION} query in OpenCL 2.1 or newer,
the {CL_DEVICE_ILS_WITH_VERSION} query in OpenCL 3.0 or newer, or the
{CL_DEVICE_IL_VERSION_KHR} query in the {cl_khr_il_program_EXT} extension.

OpenCL environments that support the {cl_khr_il_program_EXT} extension or
OpenCL 2.1 must support SPIR-V 1.0 modules.  OpenCL environments that support
OpenCL 2.2 must support SPIR-V 1.0, 1.1, and 1.2 modules.
Use the {CL_DEVICE_IL_VERSION} or {CL_DEVICE_ILS_WITH_VERSION} query
to determine the versions of SPIR-V modules that are supported by
OpenCL environments that support OpenCL 3.0.

=== Extended Instruction Sets

OpenCL environments supporting SPIR-V must support SPIR-V modules that import
the *OpenCL.std*
<<opencl-extended-instruction-set, extended instruction set for OpenCL>>
using *OpExtInstImport*. For example:

----
... = OpExtInstImport "OpenCL.std"
----

=== Source Language Encoding

If a SPIR-V module represents a program written in OpenCL C, then the
_Source Language_ operand for the *OpSource* instruction should be
*OpenCL_C*, and the 32-bit literal language _Version_ should describe the
version of OpenCL C, encoded MSB to LSB as:

    0 | Major Number | Minor Number | Revision Number (optional)

If a SPIR-V module represents a program written in OpenCL {cpp}, then the
_Source Language_ operand for the *OpSource* instruction should be
*OpenCL_CPP*, and the 32-bit literal language _Version_ should describe the
version of OpenCL {cpp}, encoded similarly.

The source language version is purely informational and has no semantic
meaning.

=== Numerical Type Formats

For all OpenCL environments, floating-point types are represented and stored
using <<ieee-754-spec, IEEE-754>> semantics.
All integer formats are represented and stored using 2's-complement format.

=== Supported Types

The following types are supported by OpenCL environments.
Note that some types may require additional capabilities, and may not be
supported by all OpenCL environments.

OpenCL environments support arrays declared using *OpTypeArray*, structs
declared using *OpTypeStruct*, functions declared using *OpTypeFunction*,
and pointers declared using *OpTypePointer*.

// TODO: This needs to be more precise, describing the restrictions
// in the OpenCL C spec section 6.9.

==== Basic Scalar and Vector Types

*OpTypeVoid* is supported.

The following scalar types are supported by OpenCL environments:

* *OpTypeBool*
* *OpTypeInt*, with _Width_ equal to 8, 16, 32, or 64, and with
  _Signedness_ equal to zero, indicating no signedness semantics.
* *OpTypeFloat*, with _Width_ equal to 16, 32, or 64.

OpenCL environments support vector types declared using *OpTypeVector*.
The vector _Component Type_ may be any of the scalar types described
above.
Supported vector _Component Counts_ are 2, 3, 4, 8, or 16.

==== Image-Related Data Types

The following table describes the *OpTypeImage* image types supported by
OpenCL environments:

.Image Types
[cols="1,1,1,3",options="header"]
|====
| _Dim_
| _Depth_
| _Arrayed_
| *Description*

// image1d_t
| *1D*
| `0`
| `0`
| A 1D image.

// image1d_array_t
| *1D*
| `0`
| `1`
| A 1D image array.

// image2d_t
| *2D*
| `0`
| `0`
| A 2D image.

// image2d_depth_t
| *2D*
| `1`
| `0`
| A 2D depth image.

// image2d_array_t
| *2D*
| `0`
| `1`
| A 2D image array.

// image2d_array_depth_t
| *2D*
| `1`
| `1`
| A 2D depth image array.

// image3d_t
| *3D*
| `0`
| `0`
| A 3D image.

// image1d_buffer_t
| *Buffer*
| `0`
| `0`
| A 1D buffer image.

|====

// These require MSAA extensions:
// image2d_msaa_t
// image2d_array_msaa_t
// image2d_msaa_depth_t
// image2d_array_msaa_depth_t

// sampler_t
*OpTypeSampler* may be used to declare sampler types in OpenCL environments.

// This cannot be passed to a kernel or expressed directly in OpenCL C but
// should be mentioned explicitly, see internal issue 273:
*OpTypeSampledImage* may be used to declare combined image and sampler types in OpenCL environments.

==== Other Data Types

The following table describes other data types that may be used in an
OpenCL environment:

.Other Data Types
[cols="1,1",options="header"]
|====
| *Type*
| *Description*

// event_t
| *OpTypeEvent*
| OpenCL event representing async copies from global to local memory and vice-versa.

// clk_event_t
| *OpTypeDeviceEvent*
| OpenCL device-side event representing commands enqueued to device command-queues.

// pipe_t
| *OpTypePipe*
| OpenCL pipe.

// reserve_id_t
| *OpTypeReserveId*
| OpenCL pipe reservation identifier.

// queue_t
| *OpTypeQueue*
| OpenCL device-side command-queue.

|====

// ndrange_t - an OpTypeStruct, see OpBuildNDRange
// kernel_enqueue_flags_t - an integer-type scalar, see Kernel Enqueue Flags
// clk_profiling_info - an integer-type scalar, see Kernel Profiling Info

=== Image Channel Order Mapping

The following table describes how the results of the SPIR-V
*OpImageQueryOrder* instruction correspond to the OpenCL host API image
channel orders.

.Image Channel Order mapping
[cols="1,5,5",options="header"]
|====
2+| *SPIR-V Image Channel Order*
| *OpenCL Image Channel Order*

| 0
| *R*
| {CL_R}

| 1
| *A*
| {CL_A}

| 2
| *RG*
| {CL_RG}

| 3
| *RA*
| {CL_RA}

| 4
| *RGB*
| {CL_RGB}

| 5
| *RGBA*
| {CL_RGBA}

| 6
| *BGRA*
| {CL_BGRA}

| 7
| *ARGB*
| {CL_ARGB}

| 8
| *Intensity*
| {CL_INTENSITY}

| 9
| *Luminance*
| {CL_LUMINANCE}

| 10
| *Rx*
| {CL_Rx}

| 11
| *RGx*
| {CL_RGx}

| 12
| *RGBx*
| {CL_RGBx}

| 13
| *Depth*
| {CL_DEPTH}

| 14
| *DepthStencil*
| {CL_DEPTH_STENCIL}

| 15
| *sRGB*
| `CL_sRGB`

| 16
| *sRGBx*
| `CL_sRGBx`

| 17
| *sRGBA*
| `CL_sRGBA`

| 18
| *sBGRA*
| `CL_sBGRA`

| 19
| *ABGR*
| {CL_ABGR}

|====

[NOTE]
--
The SPIR-V Image Channel Orders are enumerated in the same order as the
OpenCL Channel Order enums to enable simple conversion between the two.
--

=== Image Channel Data Type Mapping

The following table describes how the results of the SPIR-V
*OpImageQueryFormat* instruction correspond to the OpenCL host API image
channel data types.

.Image Channel Data Type mapping
[cols="1,5,5",options="header"]
|====
2+| *SPIR-V Image Channel Data Type*
| *OpenCL Image Channel Data Type*

| 0
| *SnormInt8*
| {CL_SNORM_INT8}

| 1
| *SnormInt16*
| {CL_SNORM_INT16}

| 2
| *UnormInt8*
| {CL_UNORM_INT8}

| 3
| *UnormInt16*
| {CL_UNORM_INT16}

| 4
| *UnormShort565*
| {CL_UNORM_SHORT_565}

| 5
| *UnormShort555*
| {CL_UNORM_SHORT_555}

| 6
| *UnormInt101010*
| {CL_UNORM_INT_101010}

| 7
| *SignedInt8*
| {CL_SIGNED_INT8}

| 8
| *SignedInt16*
| {CL_SIGNED_INT16}

| 9
| *SignedInt32*
| {CL_SIGNED_INT32}

| 10
| *UnsignedInt8*
| {CL_UNSIGNED_INT8}

| 11
| *UnsignedInt16*
| {CL_UNSIGNED_INT16}

| 12
| *UnsignedInt32*
| {CL_UNSIGNED_INT32}

| 13
| *HalfFloat*
| {CL_HALF_FLOAT}

| 14
| *Float*
| {CL_FLOAT}

| 15
| *UnormInt24*
| {CL_UNORM_INT24}

| 16
| *UnormInt101010_2*
| {CL_UNORM_INT_101010_2}

ifdef::cl_ext_image_unorm_int_2_101010[]
| 21
| *UnormInt2_101010EXT*
| {CL_UNORM_INT_2_101010_EXT}
endif::cl_ext_image_unorm_int_2_101010[]
|====

[NOTE]
--
The SPIR-V Image Channel Data Types are enumerated in the same order as the
OpenCL Channel Data Type enums to enable simple conversion between the two.
--

=== Kernels

An *OpFunction* in a SPIR-V module that is identified with *OpEntryPoint*
defines an OpenCL kernel that may be invoked using the OpenCL host API
enqueue kernel interfaces.

==== Kernel Return Types

The _Result Type_ for an *OpFunction* identified with *OpEntryPoint* must be
*OpTypeVoid*.

==== Kernel Arguments

An *OpFunctionParameter* for an *OpFunction* that is identified with
*OpEntryPoint* defines an OpenCL kernel argument.
Allowed types for OpenCL kernel arguments are:

  * *OpTypeInt*
  * *OpTypeFloat*
  * *OpTypeStruct*
  * *OpTypeVector*
  * *OpTypePointer*
  * *OpTypeSampler*
  * *OpTypeImage*
  * *OpTypePipe*
  * *OpTypeQueue*

For *OpTypeInt* parameters, supported _Widths_ are 8, 16, 32, and 64, and
must have no signedness semantics.

For *OpTypeFloat* parameters, supported _Width_ are 16, 32, and 64.

For *OpTypeStruct* parameters, supported structure _Member Types_ are:

  * *OpTypeInt*
  * *OpTypeFloat*
  * *OpTypeStruct*
  * *OpTypeVector*
  * *OpTypePointer*

For *OpTypePointer* parameters, supported _Storage Classes_ are:

  * *CrossWorkgroup*
  * *Workgroup*
  * *UniformConstant*

OpenCL kernel argument types must have a representation in the OpenCL host
API.

Environments that support extensions or optional features may allow
additional types in an entry point's parameter list.

=== Built-in Variables

An *OpVariable* in a SPIR-V module with the *BuiltIn* decoration represents
a built-in variable.
All built-in variables must be in the *Input* storage class.

The following table describes the required SPIR-V type for built-in variables.
In this table, `size_t` is used as a generic type to represent:

  * *OpTypeInt* with _Width_ equal to 32 if the _Addressing Model_ declared in *OpMemoryModel* is *Physical32*.
  * *OpTypeInt* with _Width_ equal to 64 if the _Addressing Model_ declared in *OpMemoryModel* is *Physical64*.

The mapping from an OpenCL C built-in function to the SPIR-V *BuiltIn* is informational and non-normative.

[cols="2,2,3",options="header"]
|====
|*OpenCL C Function*
|*SPIR-V BuiltIn*
|*Required SPIR-V Type*

| `get_work_dim`
 | *WorkDim*
  | *OpTypeInt* with _Width_ equal to 32

| `get_global_size`
 | *GlobalSize*
  | *OpTypeVector* of 3 components of `size_t`

| `get_global_id`
 | *GlobalInvocationId*
  | *OpTypeVector* of 3 components of `size_t`

| `get_local_size`
 | *WorkgroupSize*
  | *OpTypeVector* of 3 components of `size_t`

| `get_enqueued_local_size`
 | *EnqueuedWorkgroupSize*
  | *OpTypeVector* of 3 components of `size_t`

| `get_local_id`
 | *LocalInvocationId*
  | *OpTypeVector* of 3 components of `size_t`

| `get_num_groups`
 | *NumWorkgroups*
  | *OpTypeVector* of 3 components of `size_t`

| `get_group_id`
 | *WorkgroupId*
  | *OpTypeVector* of 3 components of `size_t`

| `get_global_offset`
 | *GlobalOffset*
  | *OpTypeVector* of 3 components of `size_t`

| `get_global_linear_id`
 | *GlobalLinearId*
  | `size_t`

| `get_local_linear_id`
 | *LocalInvocationIndex*
  | `size_t`

| `get_sub_group_size`
 | *SubgroupSize*
  | *OpTypeInt* with _Width_ equal to 32

| `get_max_sub_group_size`
 | *SubgroupMaxSize*
  | *OpTypeInt* with _Width_ equal to 32

| `get_num_sub_groups`
 | *NumSubgroups*
  | *OpTypeInt* with _Width_ equal to 32

| `get_enqueued_num_sub_groups`
 | *NumEnqueuedSubgroups*
  | *OpTypeInt* with _Width_ equal to 32

| `get_sub_group_id`
 | *SubgroupId*
  | *OpTypeInt* with _Width_ equal to 32

| `get_sub_group_local_id`
 | *SubgroupLocalInvocationId*
  | *OpTypeInt* with _Width_ equal to 32

// TODO: Ensure this is documented as part of the extension!
//| `get_sub_group_eq_mask`
// | *SubgroupEqMask*
//  | *OpTypeVector* of 4 components of *OpTypeInt* with _Width_ equal to 32
//
//| `get_sub_group_ge_mask`
// | *SubgroupGeMask*
//  | *OpTypeVector* of 4 components of *OpTypeInt* with _Width_ equal to 32
//
//| `get_sub_group_gt_mask`
// | *SubgroupGtMask*
//  | *OpTypeVector* of 4 components of *OpTypeInt* with _Width_ equal to 32
//
//| `get_sub_group_le_mask`
// | *SubgroupLeMask*
//  | *OpTypeVector* of 4 components of *OpTypeInt* with _Width_ equal to 32
//
//| `get_sub_group_lt_mask`
// | *SubgroupLtMask*
//  | *OpTypeVector* of 4 components of *OpTypeInt* with _Width_ equal to 32

|====

=== Alignment of Types

Objects of type *OpTypeInt*, *OpTypeFloat*, and *OpTypePointer* must be aligned
in memory to the size of the type in bytes. Objects of type *OpTypeVector* with
these component types must be aligned in memory to the size of the vector type
in bytes. For 3-component vector types, the size of the vector type is four
times the size the component type.

The compiler is responsible for aligning objects allocated by *OpVariable* to
the appropriate alignment as required by the _Result Type_.

For *OpTypePointer* arguments to a function, the compiler may assume that the
pointer is appropriately aligned as required by the _Type_ that the pointer
points to.

Behavior of an unaligned load or store is undefined.

=== Printf Operands

For the *printf* instruction in the *OpenCL.std*
<<opencl-extended-instruction-set, extended instruction set for OpenCL>>, the
format specifiers in the _format_ operand determine how to print the
additional argument operands.

Behavior is undefined unless the source operand type for an additional argument
matches the supported operand types for the format specifier in the following
table.

[cols="1,1,1,3",options="header"]
|====
|*Vector Specifier*
|*Length Modifier*
|*Conversion Specifier*
|*Supported Operand Type*

// Scalar Integers:

| (none)
| *hh*, *h*, (none)
| *d*, *i*, *o*, *u*, *x*, *X*
  | *OpTypeInt* with _Width_ equal to 32

| (none)
| *l*
| *d*, *i*, *o*, *u*, *x*, *X*
  | *OpTypeInt* with _Width_ equal to 64

// Scalar Floats:

| (none)
| (none)
| *a*, *A*, *e*, *E*, *f*, *F*, *g*, *G*
  | *OpTypeFloat* with _Width_ equal to 32
    footnote:[This allows printing 16-bit `half` and 32-bit `float` values on
    devices that both do and do not support the *Float64* capability for
    double-precision floating-point.], +
    *OpTypeFloat* with _Width_ equal to 64

// Vector Integers:

| **v**_n_
| *hh*
| *d*, *i*, *o*, *u*, *x*, *X*
  | *OpTypeVector* with _n_ components of *OpTypeInt* with _Width_ equal to 8

| **v**_n_
| *h*
| *d*, *i*, *o*, *u*, *x*, *X*
  | *OpTypeVector* with _n_ components of *OpTypeInt* with _Width_ equal to 16

| **v**_n_
| *hl*
| *d*, *i*, *o*, *u*, *x*, *X*
  | *OpTypeVector* with _n_ components of *OpTypeInt* with _Width_ equal to 32

| **v**_n_
| *l*
| *d*, *i*, *o*, *u*, *x*, *X*
  | *OpTypeVector* with _n_ components of *OpTypeInt* with _Width_ equal to 64

// Vector Floats:

| **v**_n_
| *h*
| *a*, *A*, *e*, *E*, *f*, *F*, *g*, *G*
  | *OpTypeVector* with _n_ components of *OpTypeFloat* with _Width_ equal to 16

| **v**_n_
| *hl*
| *a*, *A*, *e*, *E*, *f*, *F*, *g*, *G*
  | *OpTypeVector* with _n_ components of *OpTypeFloat* with _Width_ equal to 32

| **v**_n_
| *l*
| *a*, *A*, *e*, *E*, *f*, *F*, *g*, *G*
  | *OpTypeVector* with _n_ components of *OpTypeFloat* with _Width_ equal to 64

|====
