// Copyright 2017-2019 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[[introduction]]
== Introduction

<<opencl-spec, *OpenCL*>> (Open Computing Language) is an open royalty-free
standard for general purpose parallel programming across CPUs, GPUs, and
other processors, giving software developers portable and efficient access
to the power of these heterogeneous processing platforms.

Parallel programs in OpenCL may be written in the <<opencl-c-spec, OpenCL C>>
source language, or may compiled from OpenCL C, <<opencl-cpp-spec, OpenCL
{cpp}>>, or other source languages into SPIR-V modules.

All SPIR-V intermediate binary modules are consumed by environments, such as
an API, a specific version of an API, or an implementation of an API.
The environment describes required support for some SPIR-V capabilities,
additional semantics for some SPIR-V instructions, and additional validation
rules a module must adhere to in order to be considered valid.

This document describes the environment for implementations of the OpenCL
API.
It is written for compiler developers who are generating SPIR-V modules to
be consumed by the OpenCL API, for implementors of the OpenCL API who are
consuming SPIR-V modules, and by software developers who are using SPIR-V
modules with the OpenCL API.
