// Copyright 2017-2025 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[[introduction]]
== Introduction

<<opencl-spec, OpenCL>> is an open, royalty-free, standard for general
purpose parallel programming across CPUs, GPUs, and other processors, giving
software developers portable and efficient access to the power of
heterogeneous processing platforms.

<<spirv-spec, SPIR-V>> is an open, royalty-free, standard intermediate
language capable of representing parallel compute kernels that are executed
by implementations of the OpenCL standard.

SPIR-V is adaptable to multiple execution environments: a SPIR-V module is
consumed by an execution environment, as specified by a client API.
This document describes the SPIR-V execution environment for implementations
of the OpenCL standard.
The SPIR-V execution environment describes required support for some SPIR-V
capabilities, additional semantics for some SPIR-V instructions, and
additional validation rules that a SPIR-V binary module must adhere to in
order to be considered valid.

This document is written for compiler developers who are generating SPIR-V
modules intended to be consumed by the OpenCL API, for implementors of the
OpenCL API who are consuming SPIR-V modules, and for software developers who
are using SPIR-V modules with the OpenCL API.
