// Copyright 2017-2026 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[[required-capabilities]]
== Required Capabilities

[[required-capabilities-1.0]]
=== SPIR-V 1.0

An OpenCL environment that supports SPIR-V 1.0 must support SPIR-V 1.0
modules that declare the following capabilities:

  * *Addresses*
  * *Float16Buffer*
  * *Int64*
    ** For Full Profile devices.
  * *Int16*
  * *Int8*
  * *Kernel*
  * *Linkage*
  * *Vector16*
  * *DeviceEnqueue*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices supporting Device-Side Enqueue (where {CL_DEVICE_DEVICE_ENQUEUE_CAPABILITIES} is not `0`).
  * *GenericPointer*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices supporting the Generic Address Space (where {CL_DEVICE_GENERIC_ADDRESS_SPACE_SUPPORT} is {CL_TRUE}).
  * *Groups*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices supporting Sub-groups (where {CL_DEVICE_MAX_NUM_SUB_GROUPS} is not `0`) or Work-group Collective Functions (where {CL_DEVICE_WORK_GROUP_COLLECTIVE_FUNCTIONS_SUPPORT} is {CL_TRUE}).
  * *Pipes*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices supporting Pipes (where {CL_DEVICE_PIPE_SUPPORT} is {CL_TRUE}).
  * *ImageBasic*
    ** For devices supporting Images (where {CL_DEVICE_IMAGE_SUPPORT} is {CL_TRUE})
  * *Float64*
    ** For devices supporting Double Precision Floating-Point (where {CL_DEVICE_DOUBLE_FP_CONFIG} is not `0`)

If the OpenCL environment supports the *ImageBasic* capability, then
the following capabilities must also be supported:

  * *LiteralSampler*
  * *Sampled1D*
  * *Image1D*
  * *SampledBuffer*
  * *ImageBuffer*
  * *ImageReadWrite*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices supporting Read-Write Images (where {CL_DEVICE_MAX_READ_WRITE_IMAGE_ARGS} is not `0`)

[[required-capabilities-1.1]]
=== SPIR-V 1.1

An OpenCL environment supporting SPIR-V 1.1 must support SPIR-V 1.1
modules that declare the capabilities required for SPIR-V 1.0 modules,
above.

In addition, an OpenCL environment consuming SPIR-V 1.1 must support
SPIR-V 1.1 modules that declare the following capabilities:

  * *SubgroupDispatch*
    ** For OpenCL 2.2 devices, or OpenCL 3.0 devices supporting Sub-groups (where {CL_DEVICE_MAX_NUM_SUB_GROUPS} is not `0`)
// TODO: Do we need a device query for pipe storage?
//       We do not currently expose pipe storage in OpenCL C.
  * *PipeStorage*
    ** For OpenCL 2.2 devices.
// Removing these for now, see:
// https://github.com/KhronosGroup/OpenCL-Docs/issues/190
// https://github.com/KhronosGroup/OpenCL-Docs/pull/191
//  * *Initializer* (OpenCL 2.2 and Newer)
//  * *Finalizer* (OpenCL 2.2 and Newer)

[[required-capabilities-1.2]]
=== SPIR-V 1.2

An OpenCL environment supporting SPIR-V 1.2 must support SPIR-V 1.2
modules that declare the capabilities required for SPIR-V 1.1 modules,
above.

SPIR-V 1.2 does not add any new required capabilities.

[[required-capabilities-1.3]]
=== SPIR-V 1.3

An OpenCL environment supporting SPIR-V 1.3 must support SPIR-V 1.3
modules that declare the capabilities required for SPIR-V 1.2 modules,
above.

Prior to OpenCL 3.1, SPIR-V 1.3 did not add any new required capabilities.

An OpenCL environment supporting SPIR-V 1.3 and OpenCL 3.1 must support SPIR-V
1.3 modules that declare the following capabilities:

* *GroupNonUniformShuffle*
* *GroupNonUniformShuffleRelative*

For instructions requiring these capabilities, _Scope_ for _Execution_ may be:

* *Subgroup*

For the instructions *OpGroupNonUniformShuffle* and *OpGroupNonUniformShuffleXor* requiring these capabilities, valid types for _Value_ are:

* Scalars of supported types:
** *OpTypeInt* (equivalent to `char`, `uchar`, `short`, `ushort`, `int`, `uint`, `long`, and `ulong`)
** *OpTypeFloat* (equivalent to `half`, `float`, and `double`)

[[required-capabilities-1.4]]
=== SPIR-V 1.4

An OpenCL environment supporting SPIR-V 1.4 must support SPIR-V 1.4
modules that declare the capabilities required for SPIR-V 1.3 modules,
above.

SPIR-V 1.4 does not add any new required capabilities.

[[required-capabilities-1.5]]
=== SPIR-V 1.5

An OpenCL environment supporting SPIR-V 1.5 must support SPIR-V 1.5
modules that declare the capabilities required for SPIR-V 1.4 modules,
above.

SPIR-V 1.5 does not add any new required capabilities.

[[required-capabilities-1.6]]
=== SPIR-V 1.6

An OpenCL environment supporting SPIR-V 1.6 must support SPIR-V 1.6
modules that declare the capabilities required for SPIR-V 1.5 modules,
above.

Prior to OpenCL 3.1, SPIR-V 1.6 did not add any new required capabilities.

An OpenCL environment supporting SPIR-V 1.6 and OpenCL 3.1 must support SPIR-V
1.6 modules that declare the following capabilities:

* *DotProduct*
* *DotProductInput4x8Bit* if {CL_DEVICE_INTEGER_DOT_PRODUCT_INPUT_4x8BIT} is supported
* *DotProductInput4x8BitPacked*

[[required-capabilities-extensions]]
=== SPIR-V Extensions

An OpenCL environment supporting OpenCL 3.1 must support SPIR-V modules that
declare the following SPIR-V extensions via *OpExtension* and the following
extension capabilities:

* `SPV_KHR_bit_instructions`
  ** *BitInstructions*

* `SPV_KHR_integer_dot_product`
  ** *DotProductKHR*
  ** *DotProductInput4x8BitKHR* if {CL_DEVICE_INTEGER_DOT_PRODUCT_INPUT_4x8BIT_KHR} is supported
  ** *DotProductInput4x8BitPackedKHR*

* `SPV_KHR_subgroup_rotate`
  ** *GroupNonUniformRotateKHR*
