// Copyright 2017-2024 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

[[validation-rules]]
== Validation Rules

The following are a list of validation rules that apply to SPIR-V modules
executing in all OpenCL environments:

The _Execution Model_ declared in *OpEntryPoint* must be *Kernel*.

The _Addressing Model_ declared in *OpMemoryModel* must be either:

  * *Physical32* (for OpenCL devices reporting `32` for {CL_DEVICE_ADDRESS_BITS})
  * *Physical64* (for OpenCL devices reporting `64` for {CL_DEVICE_ADDRESS_BITS})
  
The _Memory Model_ declared in *OpMemoryModel* must be *OpenCL*.

For all *OpTypeInt* integer type-declaration instructions:

  * _Signedness_ must be 0, indicating no signedness semantics.
  
For all *OpTypeImage* type-declaration instructions:

  * _Sampled Type_ must be *OpTypeVoid*.
  * _Sampled_ must be 0, indicating that the image usage will be known at
     run time, not at compile time.
  * _MS_ must be 0, indicating single-sampled content.
  * _Arrayed_ may only be set to 1, indicating arrayed content, when _Dim_
     is set to *1D* or *2D*.
  * _Image Format_ must be *Unknown*, indicating that the image does not
     have a specified format.
  * The optional image _Access Qualifier_ must be present.
  
The image write instruction *OpImageWrite* must not include any optional
_Image Operands_.

The image read instructions *OpImageRead* and *OpImageSampleExplicitLod* 
must not include the optional _Image Operand_ *ConstOffset*.

For all *Atomic Instructions*:

  * Only 32-bit integer types are supported for the _Result Type_ and/or
    type of _Value_.
  * The _Pointer_ operand must be a pointer to the *Function*, *Workgroup*,
    or *CrossWorkgroup* _Storage Classes_.  Note that an *Atomic Instruction*
    on a pointer to the *Function* _Storage Class_ is valid, but does not
    have defined behavior.
  * For OpenCL environments that support and declare the *GenericPointer*
    capability, the _Pointer_ operand may be a pointer to the *Generic* 
    _Storage Class_, however behavior is still undefined if the *Generic*
    pointer represents a pointer to the *Function* _Storage Class_.

Recursion is not supported.
The static function call graph for an entry point must not contain cycles.

Whether irreducible control flow is legal is implementation-defined.

For the instructions *OpGroupAsyncCopy* and *OpGroupWaitEvents*,
_Scope_ for _Execution_ must be:

  * *Workgroup*

For the *Group and Subgroup Instructions*, _Scope_ for _Execution_ must
be one of:

  * *Workgroup*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting Work-group Collective Functions (where
       {CL_DEVICE_WORK_GROUP_COLLECTIVE_FUNCTIONS_SUPPORT} is {CL_TRUE}).
  * *Subgroup*
    ** For OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices supporting
       Sub-groups (where {CL_DEVICE_MAX_NUM_SUB_GROUPS} is not `0`)

For all other instructions, _Scope_ for _Execution_ must be one of:

  * *Workgroup*
  * *Subgroup*
    ** For OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices supporting
       Sub-groups (where {CL_DEVICE_MAX_NUM_SUB_GROUPS} is not `0`)

In an OpenCL 1.2 environment,
for the *Barrier Instructions* *OpControlBarrier* and *OpMemoryBarrier*, the
_Scope_ for _Memory_ must be *Workgroup*, and the memory-order constraint in
_Memory Semantics_ must be *SequentiallyConsistent*.
Otherwise, _Scope_ for _Memory_ must be one of:

  * *CrossDevice*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_SCOPE_ALL_DEVICES} in
       {CL_DEVICE_ATOMIC_FENCE_CAPABILITIES}.
  * *Device*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_SCOPE_DEVICE} in
       {CL_DEVICE_ATOMIC_FENCE_CAPABILITIES}.
  * *Workgroup*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_SCOPE_WORK_GROUP} in
       {CL_DEVICE_ATOMIC_FENCE_CAPABILITIES}.
  * *Subgroup*
    ** For OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices supporting
       Sub-groups (where {CL_DEVICE_MAX_NUM_SUB_GROUPS} is not `0`).
  * *Invocation*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_SCOPE_WORK_ITEM} in
       {CL_DEVICE_ATOMIC_FENCE_CAPABILITIES}.

And, the memory-order constraint in _Memory Semantics_ must be one of:

  * *None (Relaxed)*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_ORDER_RELAXED} in
       {CL_DEVICE_ATOMIC_FENCE_CAPABILITIES}.
  * *Acquire*, *Release*, or *AcquireRelease*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_ORDER_ACQ_REL} in
       {CL_DEVICE_ATOMIC_FENCE_CAPABILITIES}.
  * *SequentiallyConsistent*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_ORDER_SEQ_CST} in
       {CL_DEVICE_ATOMIC_FENCE_CAPABILITIES}.

In all OpenCL environments, for the *Barrier Instruction* *OpControlBarrier*,
when the _Scope_ for _Execution_ is *Subgroup*, behavior is undefined unless
all invocations in the sub-group execute the same dynamic instance of the
instruction.

In an OpenCL 1.2 environment,
for the *Atomic Instructions*, the _Scope_ for _Memory_ must be *Device*,
and the memory-order constraint in _Memory Semantics_ must be *Relaxed*.
Otherwise, _Scope_ for _Memory_ must be one of:

  * *CrossDevice*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_SCOPE_ALL_DEVICES} in
       {CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES}.
  * *Device*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_SCOPE_DEVICE} in
       {CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES}.
  * *Workgroup*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_SCOPE_WORK_GROUP} in
       {CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES}.
  * *Subgroup*
    ** For OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices supporting
       Sub-groups (where {CL_DEVICE_MAX_NUM_SUB_GROUPS} is not `0`).
// From the OpenCL C spec:
// memory_scope_work_item can only be used with atomic_work_item_fence
// with flags set to CLK_IMAGE_MEM_FENCE.
//  * *Invocation*

And, the memory-order constraint in _Memory Semantics_ must be one of:

  * *None (Relaxed)*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_ORDER_RELAXED} in
       {CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES}.
  * *Acquire*, *Release*, or *AcquireRelease*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_ORDER_ACQ_REL} in
       {CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES}.
  * *SequentiallyConsistent*
    ** For OpenCL 2.0, OpenCL 2.1, OpenCL 2.2, or OpenCL 3.0 devices
       supporting {CL_DEVICE_ATOMIC_ORDER_SEQ_CST} in
       {CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES}.
