// Copyright 2016-2025 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= Acknowledgements

The OpenCL specification is the result of the contributions of many people,
representing a cross section of the desktop, hand-held, and embedded
computer industry.
Following is a partial list of the contributors, including the company that
they represented at the time of their contribution:

Chuck Rose, Adobe +
Eric Berdahl, Adobe +
Shivani Gupta, Adobe +
Bill Licea Kane, AMD +
Ed Buckingham, AMD +
Jan Civlin, AMD +
Laurent Morichetti, AMD +
Mark Fowler, AMD +
Marty Johnson, AMD +
Michael Mantor, AMD +
Norm Rubin, AMD +
Ofer Rosenberg, AMD +
Brian Sumner, AMD +
Victor Odintsov, AMD +
Aaftab Munshi, Apple +
Abe Stephens, Apple +
Alexandre Namaan, Apple +
Anna Tikhonova, Apple +
Chendi Zhang, Apple +
Eric Bainville, Apple +
David Hayward, Apple +
Giridhar Murthy, Apple +
Ian Ollmann, Apple +
Inam Rahman, Apple +
James Shearer, Apple +
MonPing Wang, Apple +
Tanya Lattner, Apple +
Mikael Bourges-Sevenier, Aptina +
Brice Videau, Argonne National Laboratory +
Anton Lokhmotov, ARM +
Dave Shreiner, ARM +
Einar Hov, ARM +
Hedley Francis, ARM +
Kevin Petit, ARM +
Neil Hickey, ARM +
Robert Elliott, ARM +
Scott Moyers, ARM +
Stuart Brady, ARM +
Sven Van Haastregt, Arm +
Tom Olson, ARM +
Anastasia Stulova, ARM +
Christopher Thompson-Walsh, Broadcom +
Holger Waechtler, Broadcom +
Norman Rink, Broadcom +
Andrew Richards, Codeplay +
Maria Rovatsou, Codeplay +
Alistair Donaldson, Codeplay +
Alastair Murray, Codeplay +
Ewan Crawford, Codeplay +
Stephen Frye, Electronic Arts +
Eric Schenk, Electronic Arts +
Daniel Laroche, Freescale +
David Neto, Google +
James Price, Google +
Robin Grosman, Huawei +
Craig Davies, Huawei +
Brian Horton, IBM +
Brian Watt, IBM +
Gordon Fossum, IBM +
Greg Bellows, IBM +
Joaquin Madruga, IBM +
Mark Nutter, IBM +
Mike Perks, IBM +
Sean Wagner, IBM +
Jeremy Kemp, Imagination Technologies +
Jon Parr, Imagination Technologies +
Paul Fradgley, Imagination Technologies +
Robert Quill, Imagination Technologies +
James McCarthy, Imagination Technologies +
Jon Leech, Independent +
Aaron Kunze, Intel +
Aaron Lefohn, Intel +
Adam Lake, Intel +
Alexey Bader, Intel +
Allen Hux, Intel +
Andrew Brownsword, Intel +
Andrew Lauritzen, Intel +
Anton Zabaznov, Intel +
Bartosz Sochacki, Intel +
Ben Ashbaugh, Intel +
Boaz Ouriel, Intel +
Brian Lewis, Intel +
Filip Hazubski, Intel +
Geoff Berry, Intel +
Grzegorz Wawiorko, Intel +
Hong Jiang, Intel +
Jayanth Rao, Intel +
Josh Fryman, Intel +
Kevin Stevens, Intel +
Larry Seiler, Intel +
Michael Kinsner, Intel +
Michal Mrozek, Intel +
Mike MacPherson, Intel +
Murali Sundaresan, Intel +
Paul Lalonde, Intel +
Stephen Junkins, Intel +
Tim Foley, Intel +
Timothy Mattson, Intel +
Yariv Aridor, Intel +
Sébastien Le Duc, Kalray +
Benjamin Bergen, Los Alamos National Laboratory +
Roy Ju, Mediatek +
Bor-Sung Liang, Mediatek +
Rahul Agarwal, Mediatek +
Michal Witaszek, Mobica +
JenqKuen Lee, NTHU +
Amit Rao, NVIDIA +
Ashish Srivastava, NVIDIA +
Bastiaan Aarts, NVIDIA +
Chris Cameron, NVIDIA +
Christopher Lamb, NVIDIA +
Dibyapran Sanyal, NVIDIA +
Guatam Chakrabarti, NVIDIA +
Ian Buck, NVIDIA +
Jaydeep Marathe, NVIDIA +
Jian-Zhong Wang, NVIDIA +
Karthik Raghavan Ravi, NVIDIA +
Kedar Patil, NVIDIA +
Manjunath Kudlur, NVIDIA +
Mark Harris, NVIDIA +
Michael Gold, NVIDIA +
Neil Trevett, NVIDIA +
Nikhil Joshi, NVIDIA +
Richard Johnson, NVIDIA +
Sean Lee, NVIDIA +
Tushar Kashalikar, NVIDIA +
Vinod Grover, NVIDIA +
Xiangyun Kong, NVIDIA +
Yogesh Kini, NVIDIA +
Yuan Lin, NVIDIA +
Mayuresh Pise, NVIDIA +
Allan Tzeng, QUALCOMM +
Alex Bourd, QUALCOMM +
Andrew Gruber, QUALCOMM +
Andrzej Mamona, QUALCOMM +
Anirudh Acharya, QUALCOMM +
Balaji Calidas, QUALCOMM +
Benedict Gaster, QUALCOMM +
Bill Torzewski, QUALCOMM +
Bob Rychlik, QUALCOMM +
Chihong Zhang, QUALCOMM +
Chris Mei, QUALCOMM +
Colin Sharp, QUALCOMM +
David Garcia, QUALCOMM +
David Ligon, QUALCOMM +
Hongqiang Wang, QUALCOMM +
Jay Yun, QUALCOMM +
Jian Liu, QUALCOMM +
Joshua Kelly, QUALCOMM +
Lee Howes, QUALCOMM +
Lihan Bin, QUALCOMM +
Richard Ruigrok, QUALCOMM +
Robert J. Simpson, QUALCOMM +
Ruihao Zhang, QUALCOMM +
Samuel Pauls, QUALCOMM +
Sreelakshmi Haridas, QUALCOMM +
Sumesh Udayakumaran, QUALCOMM +
Vineet Goel, QUALCOMM +
Vlad Shimanskiy, QUALCOMM +
Yu-Chi Huang, QUALCOMM +
Yuehai Du, QUALCOMM +
Raun Krisch, Samsung +
Tasneem Brutch, Samsung +
Yoonseo Choi, Samsung +
Dennis Adams, Sony +
Pr-Anders Aronsson, Sony +
Jim Rasmusson, Sony +
Thierry Lepley, STMicroelectronics +
Anton Gorenko, StreamHPC +
Jakub Szuppe, StreamHPC +
Máté Ferenc Nagy-Egri, StreamHPC +
Vincent Hindriksen, StreamHPC +
Ajay Jayaraj, Texas Instruments +
Alan Ward, Texas Instruments +
Yuan Zhao, Texas Instruments +
Pete Curry, Texas Instruments +
Simon McIntosh-Smith, University of Bristol +
Paul Preney, University of Windsor +
Shane Peelar, University of Windsor +
Wei-Lun Kao, VeriSilicon +
Yanjun Zhang, VeriSilicon +
Brian Hutsell, Vivante +
Mike Cai, Vivante +
Sumeet Kumar, Vivante +
Xing Wang, Vivante +
Jeff Fifield, Xilinx +
Hem C. Neema, Xilinx +
Henry Styles, Xilinx +
Ralph Wittig, Xilinx +
Ronan Keryell, Xilinx +
AJ Guillon, YetiWare Inc +
