// Copyright 2023-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

[appendix]

[[extensions]]
= OpenCL Extensions (Informative)

Extensions to the OpenCL API can be defined by authors, groups of authors,
and the Khronos OpenCL Working Group.
The online Registry of extensions is available at URL

https://registry.khronos.org/OpenCL

It is possible to generate versions of the API Specification incorporating
different extensions.
At present only a subset of defined extensions can be incorporated in this
fashion.

The remainder of this appendix documents a set of extensions chosen when
this document was built.

Extensions are grouped as Khronos `khr`, multivendor `ext`, and then
alphabetically by author ID.
Within each group, extensions are listed in alphabetical order by their
names.


[[boilerplate-provisional-header]]
== Provisional Extensions

_Provisional_ OpenCL extensions described in this appendix have been
Ratified under the Khronos Intellectual Property Framework.
They are being made publicly available as provisional extensions to enable
review and feedback from the community.
While an extension is provisional, features may be added, removed, or
changed in non-backward compatible ways.

If you have feedback on a provisional extension, please create an issue on
the link:https://github.com/KhronosGroup/OpenCL-Docs/[OpenCL-Docs
repository].


== Extension Dependencies

Extensions which have dependencies on specific core versions or on other
extensions will list such dependencies.

All extensions implicitly require support for OpenCL 1.0.

include::{generated}/meta/current_extensions_appendix.txt[]
include::{generated}/meta/provisional_extensions_appendix.txt[]
include::{generated}/meta/deprecated_extensions_appendix.txt[]
