// Copyright 2023-2026 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

[appendix]

[[extensions]]
= OpenCL Extensions (Informative)

Extensions to the OpenCL API can be defined by authors, groups of authors,
and the Khronos OpenCL Working Group.
The online Registry of extensions is available at URL

https://registry.khronos.org/OpenCL

It is possible to generate versions of the API Specification incorporating
different extensions.
At present only a subset of defined extensions can be incorporated in this
fashion.

The remainder of this appendix documents a set of extensions chosen when
this document was built.

Extensions are grouped as Khronos `khr`, multivendor `ext`, and then
alphabetically by author ID.
Within each group, extensions are listed in alphabetical order by their
names.


[[naming-convention-for-optional-extensions]]
== Naming Convention for Optional Extensions

OpenCL extensions approved by the OpenCL working group use the following
naming convention:

  * A unique _name string_ of the form `"*cl_khr_<__name__>*"` is associated
    with each extension.
    If the extension is supported by an implementation, this string will be
    present in the implementation's {CL_PLATFORM_EXTENSIONS} string or
    {CL_DEVICE_EXTENSIONS} string.
  * All API functions defined by the extension will have names of the form
    *cl<__function_name__>KHR*.
  * All enumerants defined by the extension will have names of the form
    *CL_<__enum_name__>_KHR.*

Functions and enumerants defined by extensions that are promoted to
core features will have their *KHR* affix removed.
OpenCL implementations of such later revisions must also export the name
strings of promoted extensions in the {CL_PLATFORM_EXTENSIONS} or
{CL_DEVICE_EXTENSIONS} string, and support the *KHR*-affixed versions of
functions and enumerants as a transition aid.

Vendor extensions are strongly encouraged to follow a similar naming
convention:

  * A unique _name string_ of the form `"*cl_<__vendor_name__>_<__name>__*"`
    is associated with each extension.
    If the extension is supported by an implementation, this string will be
    present in the implementation's {CL_PLATFORM_EXTENSIONS} string or
    {CL_DEVICE_EXTENSIONS} string.
  * All API functions defined by the vendor extension will have names of the
    form *cl<__function_name__><__vendor_name__>*.
  * All enumerants defined by the vendor extension will have names of the
    form *CL_<__enum_name__>_<__vendor_name__>.*


[[header-conventions-for-optional-extensions]]
== Header Conventions for Optional Extensions

Function pointer typedefs must be declared for all extensions that add API
entrypoints.
These typedefs are a required part of the extension interface, to be
provided in an appropriate header (such as cl_ext.h if the extension is an
OpenCL extension, or cl_gl_ext.h if the extension is an OpenCL / OpenGL
sharing extension).

The following convention must be followed for all extensions affecting the
host API:

[source,opencl]
----
#ifndef extension_name
#define extension_name 1

// all data typedefs, token #defines, prototypes, and
// function pointer typedefs for this extension

// function pointer typedefs must use the
// following naming convention

typedef return_type
            (CL_API_CALL *clExtensionFunctionNameTAG_fn)(...);

#endif // _extension_name_
----

where `TAG` can be `KHR`, `EXT` or `vendor-specific`.

Consider, for example, the {cl_khr_gl_sharing_EXT} extension.
This extension would add the following to cl_gl_ext.h:

[source,opencl]
----
#ifndef cl_khr_gl_sharing
#define cl_khr_gl_sharing 1

// all data typedefs, token #defines, prototypes, and
// function pointer typedefs for this extension
#define CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR  -1000
#define CL_CURRENT_DEVICE_FOR_GL_CONTEXT_KHR    0x2006
#define CL_DEVICES_FOR_GL_CONTEXT_KHR           0x2007
#define CL_GL_CONTEXT_KHR                       0x2008
#define CL_EGL_DISPLAY_KHR                      0x2009
#define CL_GLX_DISPLAY_KHR                      0x200A
#define CL_WGL_HDC_KHR                          0x200B
#define CL_CGL_SHAREGROUP_KHR                   0x200C

// function pointer typedefs must use the
// following naming convention
typedef cl_int
        (CL_API_CALL *clGetGLContextInfoKHR_fn)(
            const cl_context_properties * /* properties */,
            cl_gl_context_info /* param_name */,
            size_t /* param_value_size */,
            void * /* param_value */,
            size_t * /*param_value_size_ret*/);

#endif // cl_khr_gl_sharing
----


[[boilerplate-experimental-header]]
== Experimental Extensions

_Experimental_ OpenCL extensions described in this appendix are being made
publicly available to enable review and feedback
from the community. While an extension is experimental, features may be
added, removed, or changed in non-backward compatible ways.

[NOTE]
====
Previous revisions of this specification used the term _provisional_ to denote
ratified extensions with an experimental status.
====

If you have feedback on an experimental extension, please create an issue on
the link:https://github.com/KhronosGroup/OpenCL-Docs/[OpenCL-Docs
repository].

== Extension Dependencies

Extensions which have dependencies on specific core versions or on other
extensions will list such dependencies.

All extensions implicitly require support for OpenCL 1.0.

include::{generated}/meta/current_extensions_appendix.txt[]
include::{generated}/meta/experimental_extensions_appendix.txt[]
include::{generated}/meta/deprecated_extensions_appendix.txt[]
