// Copyright 2018-2025 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}cl_ext_cxx_for_opencl.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2020-08-25
*IP Status*::
    No known IP claims.
*Contributors*::
  - Kevin Petit, Arm Ltd. +
  - Sven Van Haastregt, Arm Ltd. +
  - Anastasia Stulova, Arm Ltd. +
  - Marco Antognini, Arm Ltd. +
  - Neil Hickey, Arm Ltd. +
  - Alastair Murray, Codeplay +

=== Description

This extension adds support for building programs written using the C++ for
OpenCL kernel language documented in the *OpenCL-Docs* repository
(https://github.com/KhronosGroup/OpenCL-Docs)
with stable versions published in releases of the repository.

This extension also enables applications to query the version of the language
supported by the device compiler.

=== New Enums

  * {cl_device_info_TYPE}
  ** {CL_DEVICE_CXX_FOR_OPENCL_NUMERIC_VERSION_EXT}

=== New build option

This extension adds support for a new `CLC++` value to be passed to the
`-cl-std` build option accepted by {clBuildProgram} and {clCompileProgram}.

=== Preprocessor Macros

This extension defines a new language, instead of extending an existing
language. As such, there will be no preprocessor `#define` matching the
extension name string. Instead, dedicated preprocessor macros conveying
language version information are available as described in the C++ for
OpenCL Programming Language Documentation, section 2.2.2.2 "Predefined
macros".

=== Conformance tests

. Test that a program can successfully be compiled with `-cl-std=CLC++`.
. Test with a program compiled with `-cl-std=CLC++` that the value of the
  +__OPENCL_CPP_VERSION__+ macro agrees with the version returned by
  `CL_DEVICE_CXX_FOR_OPENCL_NUMERIC_VERSION_EXT`.

=== Version History

  * Revision 1.0.0, 2020-08-24
  ** Initial version.
