// Copyright 2022-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}cl_khr_work_group_uniform_arithmetic.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-04-29
*IP Status*::
    No known IP claims.
*Contributors*::
  - Kevin Petit, Arm Ltd.
  - Ben Ashbaugh, Intel

=== Description

{cl_khr_work_group_uniform_arithmetic_EXT} adds additional built-in work-group
collective functions to OpenCL C.
Specifically, this extension adds support for work-group scans and
reductions for the following operators:

  * Logical operations (`and`, `or`, and `xor`).
  * Bitwise operations (`and`, `or`, and `xor`).
  * Integer multiplication (`mul`).
  * Floating-point multiplication (`mul`).

See the
link:{OpenCLCSpecURL}#cl_khr_work_group_uniform_arithmetic[Work-group
Collective Uniform Arithmetic Functions] section of the OpenCL C
specification for more information.

=== Issues

. For these built-in functions, do we only want to support the types supported by the existing work-group collective functions, or do we want to support the types supported by the sub-group collective functions?
+
--
`RESOLVED`: The extension will require the same types as the existing
work-group collective functions.

The difference are the 8-bit and 16-bit types: `char`, `uchar`, `short`, and
`ushort`.
Note that `half` is already supported, if half-precision is supported.
--

=== Version History

  * Revision 1.0.0, 2022-04-29
  ** Initial version.
