// Copyright 2017-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}cl_khr_mipmap_image.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2020-04-21
*IP Status*::
    No known IP claims.

=== Description

The {cl_khr_mipmap_image_EXT} extension adds the ability to create and access
mipmapped images:

  * {clCreateImage} is extended to create mipmapped images.
  * {clCreateFromGLTexture} is extended to create a mipmapped image from a
    mipmapped GL texture.
  * {clEnqueueReadImage}, {clEnqueueWriteImage}, {clEnqueueCopyImage},
    {clEnqueueFillImage}, {clEnqueueCopyImageToBuffer},
    {clEnqueueCopyBufferToImage}, and {clEnqueueMapImage} are
    extended to operate on regions of mipmapped images.
  ** The <<image-mipmap-access, Specifying Mipmap Levels to Image
     Operations>> section describes how mipmap levels are encoded in
     existing parameters to these commands.
  * OpenCL C built-in functions are added to read from and query a mipmapped
    image.

See the link:{OpenCLCSpecURL}#cl_khr_mipmap_image[Mipmapped Image Reads and
Queries] section of the OpenCL C specification for more information.

=== Version History

  * Revision 1.0.0, 2020-04-21
  ** First assigned version.
