// Copyright 2017-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}cl_khr_create_command_queue.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2020-04-21
*IP Status*::
    No known IP claims.
*Contributors*::
    TBD

=== Description

{cl_khr_create_command_queue_EXT} allows OpenCL 1.x devices to support an
equivalent of the {clCreateCommandQueueWithProperties} API that was added in
OpenCL 2.0.
This allows OpenCL 1.x devices to support other optional extensions or
features that use the {clCreateCommandQueueWithProperties} API to specify
additional command-queue properties that cannot be specified using the
OpenCL 1.x {clCreateCommandQueue} API.

No new command-queue properties are required by this extension.
Applications may use the existing {CL_DEVICE_QUEUE_PROPERTIES} query to
determine command-queue properties that are supported by the device.

OpenCL 2.x devices may support this extension for compatibility.
In this scenario, the function added by this extension will have the same
capabilities as the core {clCreateCommandQueueWithProperties} API.
Applications that only target OpenCL 2.x devices should use the core OpenCL
2.x {clCreateCommandQueueWithProperties} API instead of this extension API.

NOTE: The type of the property value passed as {CL_QUEUE_PROPERTIES} to
{clCreateCommandQueueWithPropertiesKHR} is specified as
{cl_bitfield_TYPE} while the type passed to
{clCreateCommandQueueWithProperties} is
{cl_command_queue_properties_TYPE}.
While this is not a promotion in terms of the suffixing, both types
are aliased to {cl_ulong_TYPE}, so no ABI or compiler issues should
result if the extension and core APIs are supported.


=== New Commands

  * {clCreateCommandQueueWithPropertiesKHR}

=== New Types

  * {cl_queue_properties_khr_TYPE}

//@ TODO Missing bitfield values allowed for CL_QUEUE_PROPERTIES?

=== Version History

  * Revision 1.0.0, 2020-04-21
  ** First assigned version.
