// Copyright 2017-2023 The Khronos Group.
// SPDX-License-Identifier: CC-BY-4.0

//@ TODO Merge with cl_khr_gl_sharing__context - it's all one extension (I think)

include::{generated}/meta/{refprefix}cl_khr_gl_sharing__memobjs.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2020-04-21
*IP Status*::
    No known IP claims.
*Contributors*::
    TBD

=== Description

`cl_khr_gl_sharing` allows use of OpenGL buffer, texture, and renderbuffer
objects as OpenCL memory objects.
OpenCL memory objects may be created from OpenGL objects if and only if the
OpenCL context is associated with an OpenGL context or share group object.
The section <<cl_khr_gl_sharing,Creating an OpenCL Context from an OpenGL
Context or Share Group>> describes how to create an OpenCL context
associated with an OpenGL context or share group object.

An OpenCL image object may be created from an OpenGL texture or renderbuffer
object.
An OpenCL buffer object may be created from an OpenGL buffer object.

Any supported OpenGL object defined within the associated OpenGL context or
share group object may be shared, with the exception of the default OpenGL
objects (i.e. objects named zero), which may not be shared.

//@ TODO Add summary of interfaces here

=== Version History

  * Revision 1.0.0, 2020-04-21
  ** First assigned version.
