// Copyright 2017-2025 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}cl_khr_spir.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2020-04-21
*IP Status*::
    No known IP claims.

=== Description

{cl_khr_spir_EXT} adds the ability to create an OpenCL program object from a
Standard Portable Intermediate Representation (SPIR) instance.
A SPIR instance is a vendor-neutral non-source representation for OpenCL C
programs.

See the <<spir-compilation-options, SPIR Compilation Options>> for
information on compiling SPIR binaries.

{cl_khr_spir_EXT} has been superseded by the SPIR-V intermediate representation,
which is supported by the {cl_khr_il_program_EXT} extension, and is a core
feature in OpenCL 2.1.

=== New Enums

  * {cl_device_info_TYPE}
  ** {CL_DEVICE_SPIR_VERSIONS}
  * {cl_program_binary_type_TYPE}
  ** {CL_PROGRAM_BINARY_TYPE_INTERMEDIATE}

=== Version History

  * Revision 1.0.0, 2020-04-21
  ** First assigned version.
