// Copyright 2017-2025 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}cl_khr_throttle_hints.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2020-04-21
*IP Status*::
    No known IP claims.

=== Description

The {cl_khr_throttle_hints_EXT} extension adds throttle hints for OpenCL, but
does not specify the throttling behavior or minimum guarantees.
It is expected that the user guide associated with each implementation which
supports this extension will describe the throttling behavior guarantees.

Note that the throttle hint is orthogonal to functionality defined in
{cl_khr_priority_hints_EXT} extension.
For example, a task may have high priority ({CL_QUEUE_PRIORITY_HIGH_KHR})
but should at the same time be executed at an optimized throttle setting
({CL_QUEUE_THROTTLE_LOW_KHR}).

=== New Types

  * {cl_queue_throttle_khr_TYPE}

=== New Enums

  * {cl_queue_properties_TYPE}
  ** {CL_QUEUE_THROTTLE_KHR}
  * {cl_queue_throttle_khr_TYPE}
  ** {CL_QUEUE_THROTTLE_HIGH_KHR}
  ** {CL_QUEUE_THROTTLE_MED_KHR}
  ** {CL_QUEUE_THROTTLE_LOW_KHR}


=== Version History

  * Revision 1.0.0, 2020-04-21
  ** First assigned version.
