// Copyright 2018-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}cl_khr_pci_bus_info.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2021-04-19
*IP Status*::
    No known IP claims.

=== Description

The {cl_khr_pci_bus_info_EXT} extension adds a new query to obtain PCI bus
information about an OpenCL device.

Not all OpenCL devices have PCI bus information, either due to the device
not being connected to the system through a PCI interface or due to platform
specific restrictions and policies.
Thus this extension is only expected to be supported by OpenCL devices which
can provide the information.

As a consequence, applications should always check for the presence of the
extension string for each individual OpenCL device for which they intend to
issue the new query for and should not have any assumptions about the
availability of the extension on any given platform.

=== New Types

  * {cl_device_pci_bus_info_khr_TYPE}

=== New Enums

  * {cl_device_info_TYPE}
  ** {CL_DEVICE_PCI_BUS_INFO_KHR}

=== Version History

  * Revision 1.0.0, 2021-04-19
  ** Initial version.
