// Copyright 2017-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}cl_khr_terminate_context.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2020-04-21
*IP Status*::
    No known IP claims.
*Contributors*::
    TBD

=== Description

The `cl_khr_terminate_context` extension provides a new query to check
whether a device can terminate an OpenCL context, and adds an API to
terminate a context.

Today, OpenCL provides an API to release a context.
This operation is done only after all queues, memory object, programs and
kernels are released, which in turn might wait for all ongoing operations to
complete.
However, there are cases in which a fast release is required, or release
operation cannot be done, as commands are stuck in mid execution.
An example of the first case can be program termination due to exception, or
quick shutdown due to low power.
Examples of the second case are when a kernel is running too long, or gets
stuck, or it may result from user action which makes the results of the
computation unnecessary.

In many cases, the driver or the device is capable of speeding up the
closure of ongoing operations when the results are no longer required in a
much more expedient manner than waiting for all previously enqueued
operations to finish.

=== New Types

  * {cl_device_terminate_capability_khr_TYPE}

=== New Commands

  * {clTerminateContextKHR}

=== New Enums

  * {cl_device_info_TYPE}
  ** {CL_DEVICE_TERMINATE_CAPABILITY_KHR}
  * {cl_context_properties_TYPE}
  ** {CL_CONTEXT_TERMINATE_KHR}
  * {cl_device_terminate_capability_khr_TYPE}
  ** {CL_DEVICE_TERMINATE_CAPABILITY_CONTEXT_KHR}
  * New Error codes
  ** {CL_CONTEXT_TERMINATED_KHR}

=== Version History

  * Revision 1.0.0, 2020-04-21
  ** First assigned version.
