// Copyright 2017-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}cl_khr_subgroups.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2020-04-21
*IP Status*::
    No known IP claims.
*Contributors*::
    TBD

=== Description

`cl_khr_subgroups` adds support for implementation-controlled groups of work
items, known as sub-groups.
Sub-groups behave similarly to work-groups and have their own sets of
built-ins and synchronization primitives.
Sub-groups within a work-group are independent, may make forward progress
with respect to each other, and may map to optimized hardware structures
where that makes sense.

Sub-groups were promoted to a core feature in OpenCL 2.1.
However, note that:

  * The sub-group OpenCL C built-in functions described by this extension
    must still be accessed as an OpenCL C extension in OpenCL 2.1.
  * Sub-group independent forward progress is an optional device property in
    OpenCL 2.1, see {CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS}.

See the link:{OpenCLCSpecURL}#cl_khr_subgroups[Sub-Groups] section of the
OpenCL C specification for more information.

=== New Types

  * {cl_kernel_sub_group_info}

=== New Commands

  * {clGetKernelSubGroupInfoKHR}

=== New Enums

  * {cl_kernel_sub_group_info_TYPE}
  ** {CL_KERNEL_MAX_SUB_GROUP_SIZE_FOR_NDRANGE_KHR}
  ** {CL_KERNEL_SUB_GROUP_COUNT_FOR_NDRANGE_KHR}

=== Version History

  * Revision 1.0.0, 2020-04-21
  ** First assigned version.
