// Copyright 2018-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}cl_khr_suggested_local_work_size.txt[]

=== Other Extension Metadata

*Last Modified Date*::
    2021-04-22
*IP Status*::
    No known IP claims.
*Contributors*::
    TBD

=== Description

{cl_khr_suggested_local_work_size_EXT} adds the ability to query a suggested
local work-group size for a kernel running on a device for a specified
global work size and global work offset.
The suggested local work-group size will match the work-group size that
would be chosen if the kernel were enqueued with the specified global work
size and global work offset and a `NULL` local work size.

By using the suggested local work-group size query an application has
greater insight into the local work-group size chosen by the OpenCL
implementation, and the OpenCL implementation need not re-compute the local
work-group size if the same kernel is enqueued multiple times with the same
parameters.

=== New Commands

  * {clGetKernelSuggestedLocalWorkSizeKHR}

=== Version History

  * Revision 1.0.0, 2021-04-22
  ** Initial version.
