// Copyright 2017-2020 The Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

= Associated OpenCL specification


[[spirv-il]]
== SPIR-V Intermediate language

OpenCL 2.1 and 2.2 require support for the SPIR-V intermediate
language that allows offline, or linked online, compilation to a binary
format that may be consumed by the {clCreateProgramWithIL} interface.

The OpenCL specification includes a specification for the SPIR-V
intermediate language as a cross-platform input language.
In addition, platform vendors may support their own IL if this is
appropriate.
The OpenCL runtime will return a list of supported IL versions using the
{CL_DEVICE_IL_VERSION} parameter to the {clGetDeviceInfo} query.


[[opencl-extensions]]
== Extensions to OpenCL

In addition to the specification of core features, OpenCL provides a number
of extensions to the API, kernel language or intermediate representation.
These features are defined in the OpenCL 2.2 extensions specification
document.

Extensions defined against earlier versions of the OpenCL specifications,
whether the API or language specification, are defined in the matching
versions of the extension specification document.


== Support for earlier OpenCL C kernel languages

The OpenCL C kernel language is not defined in the OpenCL unified
specification.
New language features are described in the OpenCL {cpp} specification as well
as the SPIR-V specification and in kernel languages that target it.
A kernel language defined by any of the OpenCL 1.0, OpenCL 1.1, OpenCL 1.2
and OpenCL 2.0 kernel language specifications as well as kernels language
extensions defined by the matching versions of OpenCL extension
specifications are valid to pass to {clCreateProgramWithSource} executing
against an OpenCL runtime of at least that version.

