// Copyright 2017-2026 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= Associated OpenCL Specifications


[[opencl-c-kernel-language]]
== The OpenCL C Kernel Language

The OpenCL C kernel language is defined in the OpenCL C unified
specification, which specifies all versions of OpenCL C.
When an OpenCL device supports one or more versions of the OpenCL C kernel
language (see {CL_DEVICE_OPENCL_C_VERSION} and
{CL_DEVICE_OPENCL_C_ALL_VERSIONS}), OpenCL program objects may be created by
passing OpenCL C source strings to {clCreateProgramWithSource}.


[[spirv-il]]
== SPIR-V Intermediate Language

The OpenCL specifications include the SPIR-V specification, which defines a
cross-platform intermediate language.
When an OpenCL device supports one or more versions of SPIR-V (see
{CL_DEVICE_IL_VERSION} or {CL_DEVICE_ILS_WITH_VERSION}), OpenCL program objects
may be created by passing SPIR-V to {clCreateProgramWithIL}.


[[opencl-extensions]]
== Extensions to OpenCL

In addition to the specification of core features, OpenCL provides a number
of extensions to the API, kernel language, or intermediate representation.
These extensions are described in the OpenCL specifications or in vendor-provided
documentation.

