name: Presubmit

permissions:
  contents: read

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install required packages
        run: |
          sudo apt-get install -y libpango1.0-dev libwebp-dev ghostscript fonts-lyx jing
          sudo gem install asciidoctor -v 2.0.16
          sudo gem install coderay -v 1.1.1
          sudo gem install rouge -v 3.19.0
          sudo gem install ttfunk -v 1.7.0
          sudo gem install hexapdf -v 0.27.0
          sudo gem install asciidoctor-pdf -v 2.3.4
          sudo gem install asciidoctor-mathematical -v 0.3.5

      - name: List git tag
        run: |
          git describe --tags --dirty

      - name: Generate all specs
        run: |
          make -O -j 5 api c env ext cxx4opencl
          
      - name: Generate extension specs
        run: |
          make extensionshtml

      - name: Generate reference pages
        run: |
          make -O -j 5 manhtmlpages

      - name: Validate XML
        run: |
          make -C xml validate
